"""
Tests for Week 1 Items 1 & 2:
  - Item 1: Workflow Summary Panel (inject into HTML report top-level)
  - Item 2: Workflow Coverage Metrics (5th coverage dimension)

Target: ~60 tests covering unit, integration, and edge cases.
"""
import json
import os
import pytest
import tempfile
from pathlib import Path
from unittest.mock import MagicMock, patch
from dataclasses import dataclass, field


# ============================================================
# Test fixtures — shared HTML report template and workflow data
# ============================================================

MINIMAL_HTML_REPORT = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>AI SimTest Report — Test</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.min.js"></script>
<style>
:root {
  --bg: #0c0e14; --surface: #151822; --surface2: #1c2030; --border: #2a2f42;
  --text: #e2e4ec; --dim: #8890a8; --pass: #6ee7b7; --warn: #fbbf24; --fail: #f87171;
  --accent: #38bdf8;
}
</style>
</head>
<body>

<header>
  <div class="header-top">
    <h1>AI SimTest Report</h1>
  </div>
</header>

<!-- Stats Row -->
<div class="stats-row">
  <div class="stat-card">
    <div class="stat-value">5</div>
    <div class="stat-label">Personas</div>
  </div>
  <div class="stat-card">
    <div class="stat-value">5</div>
    <div class="stat-label">Conversations</div>
  </div>
  <div class="stat-card">
    <div class="stat-value">25</div>
    <div class="stat-label">Turns Judged</div>
  </div>
  <div class="stat-card">
    <div class="stat-value pass">80%</div>
    <div class="stat-label">Pass Rate</div>
  </div>
</div>

<!-- Charts Row -->
<div class="charts-row">
  <div class="chart-card">
    <h3>Judge Scores</h3>
    <canvas id="judgeChart" height="220"></canvas>
  </div>
  <div class="chart-card">
    <h3>Turn Labels</h3>
    <canvas id="labelChart" height="220"></canvas>
  </div>
</div>

<section class="section">
  <h2>👥 Persona Results</h2>
</section>

<section class="section">
  <h2>💬 Conversation Transcripts</h2>
</section>

<footer>
  Generated by <strong>AI SimTest</strong>
</footer>

<script>
// Judge Chart placeholder
new Chart(document.getElementById('judgeChart'), {type:'bar',data:{labels:['grounding'],datasets:[{data:[85]}]}});
</script>

</body>
</html>"""


def _sample_workflow_exports(n_workflows=1, n_convos=5, pass_rate=0.8):
    """Generate sample workflow export dicts for testing."""
    exports = []
    for i in range(n_workflows):
        passed = int(n_convos * pass_rate)
        failed = n_convos - passed
        results = []
        for j in range(n_convos):
            is_pass = j < passed
            results.append({
                "workflow": f"Test Workflow {i+1}",
                "domain": "customer_service",
                "passed": is_pass,
                "status": "passed" if is_pass else "failed",
                "score": 0.85 if is_pass else 0.45,
                "step_score": 0.9 if is_pass else 0.4,
                "rule_score": 1.0 if is_pass else 0.5,
                "condition_score": 0.8 if is_pass else 0.3,
                "completed_steps": ["Greeting", "Identify Issue", "Resolve"],
                "missed_steps": [] if is_pass else ["Confirm Resolution"],
                "violations": [] if is_pass else ["Required phrase missing"],
                "critical_failure": False,
                "critical_failures_count": 0,
                "workflow_applicable": True,
                "step_results": [
                    {"step_name": "Greeting", "step_id": "s1", "status": "completed", "required": True},
                    {"step_name": "Identify Issue", "step_id": "s2", "status": "completed", "required": True},
                    {"step_name": "Resolve", "step_id": "s3", "status": "completed" if is_pass else "missed", "required": True},
                    {"step_name": "Confirm Resolution", "step_id": "s4", "status": "completed" if is_pass else "missed", "required": True},
                    {"step_name": "Follow Up", "step_id": "s5", "status": "partial", "required": False},
                ],
            })

        exports.append({
            "workflow": f"Test Workflow {i+1}",
            "domain": "customer_service",
            "total_conversations": n_convos,
            "passed": passed,
            "failed": failed,
            "avg_score": round((0.85 * passed + 0.45 * failed) / n_convos, 3),
            "critical_failures": 0,
            "results": results,
        })
    return exports


@pytest.fixture
def tmp_html(tmp_path):
    """Create a temporary HTML report file."""
    p = tmp_path / "report.html"
    p.write_text(MINIMAL_HTML_REPORT, encoding="utf-8")
    return p


@pytest.fixture
def sample_exports():
    """Single workflow with 5 conversations."""
    return _sample_workflow_exports(1, 5, 0.8)


@pytest.fixture
def multi_workflow_exports():
    """Multiple workflows for testing."""
    return _sample_workflow_exports(3, 7, 0.7)


# ============================================================
# PART 1: Workflow Summary Panel Tests (Item 1)
# ============================================================

class TestWorkflowSummaryPanelInjection:
    """Test injecting workflow summary into HTML report top-level."""

    def test_basic_injection_succeeds(self, tmp_html, sample_exports):
        from src.workflow_judge.workflow_summary_panel import inject_workflow_summary_into_report
        result = inject_workflow_summary_into_report(tmp_html, sample_exports)
        assert result is True

    def test_stat_cards_injected(self, tmp_html, sample_exports):
        from src.workflow_judge.workflow_summary_panel import inject_workflow_summary_into_report
        inject_workflow_summary_into_report(tmp_html, sample_exports)
        content = tmp_html.read_text()
        assert "Workflow Pass Rate" in content
        assert "Workflow Violations" in content

    def test_compliance_banner_injected(self, tmp_html, sample_exports):
        from src.workflow_judge.workflow_summary_panel import inject_workflow_summary_into_report
        inject_workflow_summary_into_report(tmp_html, sample_exports)
        content = tmp_html.read_text()
        assert "WorkflowSummaryPanel" in content
        assert "workflow(s) evaluated" in content

    def test_chart_injected(self, tmp_html, sample_exports):
        from src.workflow_judge.workflow_summary_panel import inject_workflow_summary_into_report
        inject_workflow_summary_into_report(tmp_html, sample_exports)
        content = tmp_html.read_text()
        assert "workflowOverviewChart" in content
        assert "Workflow Scores" in content

    def test_chart_js_code_injected(self, tmp_html, sample_exports):
        from src.workflow_judge.workflow_summary_panel import inject_workflow_summary_into_report
        inject_workflow_summary_into_report(tmp_html, sample_exports)
        content = tmp_html.read_text()
        assert "Workflow Overview Chart" in content
        assert "workflowOverviewChart" in content

    def test_idempotent_second_injection_skipped(self, tmp_html, sample_exports):
        from src.workflow_judge.workflow_summary_panel import inject_workflow_summary_into_report
        inject_workflow_summary_into_report(tmp_html, sample_exports)
        content_first = tmp_html.read_text()
        result = inject_workflow_summary_into_report(tmp_html, sample_exports)
        assert result is False
        content_second = tmp_html.read_text()
        assert content_first == content_second

    def test_nonexistent_file_returns_false(self, tmp_path, sample_exports):
        from src.workflow_judge.workflow_summary_panel import inject_workflow_summary_into_report
        result = inject_workflow_summary_into_report(tmp_path / "nope.html", sample_exports)
        assert result is False

    def test_empty_exports_returns_false(self, tmp_html):
        from src.workflow_judge.workflow_summary_panel import inject_workflow_summary_into_report
        result = inject_workflow_summary_into_report(tmp_html, [])
        assert result is False

    def test_all_passed_shows_green_status(self, tmp_html):
        from src.workflow_judge.workflow_summary_panel import inject_workflow_summary_into_report
        exports = _sample_workflow_exports(1, 5, 1.0)
        inject_workflow_summary_into_report(tmp_html, exports)
        content = tmp_html.read_text()
        assert "ALL WORKFLOWS PASSED" in content

    def test_partial_shows_warning_status(self, tmp_html):
        from src.workflow_judge.workflow_summary_panel import inject_workflow_summary_into_report
        exports = _sample_workflow_exports(1, 5, 0.6)
        inject_workflow_summary_into_report(tmp_html, exports)
        content = tmp_html.read_text()
        assert "PARTIAL COMPLIANCE" in content

    def test_all_failed_shows_red_status(self, tmp_html):
        from src.workflow_judge.workflow_summary_panel import inject_workflow_summary_into_report
        exports = _sample_workflow_exports(1, 5, 0.0)
        inject_workflow_summary_into_report(tmp_html, exports)
        content = tmp_html.read_text()
        assert "ALL WORKFLOWS FAILED" in content

    def test_critical_violations_shows_alert(self, tmp_html):
        from src.workflow_judge.workflow_summary_panel import inject_workflow_summary_into_report
        exports = _sample_workflow_exports(1, 5, 0.4)
        exports[0]["critical_failures"] = 3
        inject_workflow_summary_into_report(tmp_html, exports)
        content = tmp_html.read_text()
        assert "CRITICAL VIOLATIONS" in content

    def test_multi_workflow_names_displayed(self, tmp_html, multi_workflow_exports):
        from src.workflow_judge.workflow_summary_panel import inject_workflow_summary_into_report
        inject_workflow_summary_into_report(tmp_html, multi_workflow_exports)
        content = tmp_html.read_text()
        assert "Test Workflow 1" in content
        assert "Test Workflow 2" in content
        assert "Test Workflow 3" in content

    def test_multi_workflow_chart_has_multiple_bars(self, tmp_html, multi_workflow_exports):
        from src.workflow_judge.workflow_summary_panel import inject_workflow_summary_into_report
        inject_workflow_summary_into_report(tmp_html, multi_workflow_exports)
        content = tmp_html.read_text()
        # Chart labels should have all 3 workflow names
        assert '"Test Workflow 1"' in content
        assert '"Test Workflow 2"' in content
        assert '"Test Workflow 3"' in content

    def test_pass_rate_calculation_correct(self, tmp_html):
        from src.workflow_judge.workflow_summary_panel import inject_workflow_summary_into_report
        exports = [{"workflow": "WF", "domain": "test", "total_conversations": 10,
                     "passed": 7, "failed": 3, "avg_score": 0.75, "critical_failures": 0}]
        inject_workflow_summary_into_report(tmp_html, exports)
        content = tmp_html.read_text()
        assert "70%" in content  # 7/10

    def test_html_escaping_in_workflow_names(self, tmp_html):
        from src.workflow_judge.workflow_summary_panel import inject_workflow_summary_into_report
        exports = [{"workflow": "<script>alert('xss')</script>", "domain": "test",
                     "total_conversations": 5, "passed": 5, "failed": 0,
                     "avg_score": 0.9, "critical_failures": 0}]
        inject_workflow_summary_into_report(tmp_html, exports)
        content = tmp_html.read_text()
        assert "<script>alert" not in content
        assert "&lt;script&gt;" in content

    def test_preserves_original_stat_cards(self, tmp_html, sample_exports):
        from src.workflow_judge.workflow_summary_panel import inject_workflow_summary_into_report
        inject_workflow_summary_into_report(tmp_html, sample_exports)
        content = tmp_html.read_text()
        assert "Personas" in content
        assert "Conversations" in content
        assert "Turns Judged" in content
        assert "Pass Rate" in content

    def test_preserves_original_charts(self, tmp_html, sample_exports):
        from src.workflow_judge.workflow_summary_panel import inject_workflow_summary_into_report
        inject_workflow_summary_into_report(tmp_html, sample_exports)
        content = tmp_html.read_text()
        assert "judgeChart" in content
        assert "labelChart" in content

    def test_banner_placed_before_charts(self, tmp_html, sample_exports):
        from src.workflow_judge.workflow_summary_panel import inject_workflow_summary_into_report
        inject_workflow_summary_into_report(tmp_html, sample_exports)
        content = tmp_html.read_text()
        banner_pos = content.find("WorkflowSummaryPanel")
        charts_pos = content.find("charts-row")
        assert banner_pos < charts_pos


class TestWorkflowSummaryHelpers:
    """Test helper functions."""

    def test_score_class_pass(self):
        from src.workflow_judge.workflow_summary_panel import _score_class
        assert _score_class(0.85) == "pass"
        assert _score_class(0.80) == "pass"

    def test_score_class_warn(self):
        from src.workflow_judge.workflow_summary_panel import _score_class
        assert _score_class(0.65) == "warn"
        assert _score_class(0.50) == "warn"

    def test_score_class_fail(self):
        from src.workflow_judge.workflow_summary_panel import _score_class
        assert _score_class(0.3) == "fail"
        assert _score_class(0.0) == "fail"

    def test_score_color_pass(self):
        from src.workflow_judge.workflow_summary_panel import _score_color
        assert _score_color(0.9) == "#6ee7b7"

    def test_score_color_warn(self):
        from src.workflow_judge.workflow_summary_panel import _score_color
        assert _score_color(0.6) == "#fbbf24"

    def test_score_color_fail(self):
        from src.workflow_judge.workflow_summary_panel import _score_color
        assert _score_color(0.2) == "#f87171"

    def test_find_stats_row_closing(self):
        from src.workflow_judge.workflow_summary_panel import _find_stats_row_closing
        html = '<div class="stats-row"><div class="stat-card">X</div><div class="stat-card">Y</div></div>'
        pos = _find_stats_row_closing(html)
        assert pos > 0
        assert html[pos:pos + 6] == "</div>"

    def test_find_closing_div_nested(self):
        from src.workflow_judge.workflow_summary_panel import _find_closing_div
        html = '<div class="outer"><div class="inner">A</div><div class="inner2">B</div></div>'
        pos = _find_closing_div(html, html.find("outer"))
        assert pos > 0
        # The closing div should be the outer one
        remaining = html[pos:]
        assert remaining == "</div>"


# ============================================================
# PART 2: Workflow Coverage Tests (Item 2)
# ============================================================

class TestWorkflowCoverageAnalysis:
    """Test workflow step coverage analysis."""

    def test_empty_exports_returns_zero_coverage(self):
        from src.coverage.workflow_coverage import analyze_workflow_coverage
        wc = analyze_workflow_coverage([])
        assert wc.score == 0.0
        assert wc.total_steps_defined == 0

    def test_single_workflow_basic_metrics(self, sample_exports):
        from src.coverage.workflow_coverage import analyze_workflow_coverage
        wc = analyze_workflow_coverage(sample_exports)
        assert wc.total_conversations == 5
        assert wc.total_passed == 4
        assert wc.total_failed == 1
        assert len(wc.workflows_evaluated) == 1

    def test_workflow_pass_rate(self, sample_exports):
        from src.coverage.workflow_coverage import analyze_workflow_coverage
        wc = analyze_workflow_coverage(sample_exports)
        assert wc.workflow_pass_rate == pytest.approx(0.8, abs=0.01)

    def test_step_details_populated(self, sample_exports):
        from src.coverage.workflow_coverage import analyze_workflow_coverage
        wc = analyze_workflow_coverage(sample_exports)
        assert wc.total_steps_defined > 0
        assert len(wc.step_details) > 0

    def test_step_completion_rates(self, sample_exports):
        from src.coverage.workflow_coverage import analyze_workflow_coverage
        wc = analyze_workflow_coverage(sample_exports)
        # Greeting should be completed in all conversations
        greeting_steps = [s for s in wc.step_details if "Greeting" in s.step_name]
        assert len(greeting_steps) == 1
        assert greeting_steps[0].completion_rate == 1.0

    def test_partially_exercised_steps(self, sample_exports):
        from src.coverage.workflow_coverage import analyze_workflow_coverage
        wc = analyze_workflow_coverage(sample_exports)
        # Confirm Resolution is missed in 1/5 conversations
        confirm_steps = [s for s in wc.step_details if "Confirm" in s.step_name]
        assert len(confirm_steps) == 1
        assert confirm_steps[0].times_missed == 1
        assert confirm_steps[0].times_completed == 4

    def test_optional_step_tracked(self, sample_exports):
        from src.coverage.workflow_coverage import analyze_workflow_coverage
        wc = analyze_workflow_coverage(sample_exports)
        followup = [s for s in wc.step_details if "Follow" in s.step_name]
        assert len(followup) == 1
        assert followup[0].required is False
        assert followup[0].times_partial > 0

    def test_never_exercised_steps_detected(self):
        from src.coverage.workflow_coverage import analyze_workflow_coverage
        exports = [{
            "workflow": "WF", "domain": "test",
            "total_conversations": 3, "passed": 0, "failed": 3,
            "avg_score": 0.2, "critical_failures": 0,
            "results": [
                {"status": "failed", "completed_steps": ["A"], "missed_steps": ["B", "C"],
                 "step_results": [
                     {"step_name": "A", "step_id": "s1", "status": "completed", "required": True},
                     {"step_name": "B", "step_id": "s2", "status": "missed", "required": True},
                     {"step_name": "C", "step_id": "s3", "status": "missed", "required": True},
                 ]},
            ] * 3,
        }]
        wc = analyze_workflow_coverage(exports)
        assert "B" in wc.never_exercised_steps or wc.steps_never_exercised > 0

    def test_multi_workflow_aggregation(self, multi_workflow_exports):
        from src.coverage.workflow_coverage import analyze_workflow_coverage
        wc = analyze_workflow_coverage(multi_workflow_exports)
        assert len(wc.workflows_evaluated) == 3
        assert wc.total_conversations == 21  # 3 workflows × 7 conversations

    def test_score_ranges_valid(self, sample_exports):
        from src.coverage.workflow_coverage import analyze_workflow_coverage
        wc = analyze_workflow_coverage(sample_exports)
        assert 0.0 <= wc.score <= 1.0
        assert 0.0 <= wc.step_coverage_score <= 1.0
        assert 0.0 <= wc.workflow_pass_rate <= 1.0

    def test_critical_failures_tracked(self):
        from src.coverage.workflow_coverage import analyze_workflow_coverage
        exports = [{
            "workflow": "WF", "domain": "test",
            "total_conversations": 5, "passed": 2, "failed": 3,
            "avg_score": 0.5, "critical_failures": 2,
            "results": [],
        }]
        wc = analyze_workflow_coverage(exports)
        assert wc.total_critical == 2

    def test_zero_critical_bonus(self, sample_exports):
        from src.coverage.workflow_coverage import analyze_workflow_coverage
        wc = analyze_workflow_coverage(sample_exports)
        # No critical failures → 10% bonus applies
        # Score should be higher than without bonus
        assert wc.score > wc.step_coverage_score * 0.60 + wc.workflow_pass_rate * 0.30

    def test_skipped_results_excluded(self):
        from src.coverage.workflow_coverage import analyze_workflow_coverage
        exports = [{
            "workflow": "WF", "domain": "test",
            "total_conversations": 3, "passed": 1, "failed": 1,
            "avg_score": 0.7, "critical_failures": 0,
            "results": [
                {"status": "passed", "step_results": [
                    {"step_name": "A", "step_id": "s1", "status": "completed", "required": True},
                ]},
                {"status": "failed", "step_results": [
                    {"step_name": "A", "step_id": "s1", "status": "missed", "required": True},
                ]},
                {"status": "skipped_not_applicable", "step_results": []},
            ],
        }]
        wc = analyze_workflow_coverage(exports)
        a_step = [s for s in wc.step_details if s.step_name == "A"]
        assert len(a_step) == 1
        assert a_step[0].total_evaluated == 2  # skipped one excluded

    def test_fallback_to_completed_missed_lists(self):
        from src.coverage.workflow_coverage import analyze_workflow_coverage
        exports = [{
            "workflow": "WF", "domain": "test",
            "total_conversations": 2, "passed": 1, "failed": 1,
            "avg_score": 0.6, "critical_failures": 0,
            "results": [
                {"status": "passed", "completed_steps": ["A", "B"], "missed_steps": []},
                {"status": "failed", "completed_steps": ["A"], "missed_steps": ["B"]},
            ],
        }]
        wc = analyze_workflow_coverage(exports)
        a_step = [s for s in wc.step_details if s.step_name == "A"]
        assert a_step[0].times_completed == 2
        b_step = [s for s in wc.step_details if s.step_name == "B"]
        assert b_step[0].times_completed == 1
        assert b_step[0].times_missed == 1


class TestWorkflowCoverageSerialization:
    """Test to_dict / from_dict round-trip."""

    def test_to_dict_has_required_keys(self, sample_exports):
        from src.coverage.workflow_coverage import analyze_workflow_coverage
        wc = analyze_workflow_coverage(sample_exports)
        d = wc.to_dict()
        assert "score" in d
        assert "workflows_evaluated" in d
        assert "step_details" in d
        assert "never_exercised_steps" in d

    def test_round_trip_preserves_data(self, sample_exports):
        from src.coverage.workflow_coverage import analyze_workflow_coverage, WorkflowCoverage
        wc = analyze_workflow_coverage(sample_exports)
        d = wc.to_dict()
        wc2 = WorkflowCoverage.from_dict(d)
        assert wc2.score == pytest.approx(wc.score, abs=0.001)
        assert wc2.total_conversations == wc.total_conversations
        assert wc2.total_passed == wc.total_passed
        assert len(wc2.step_details) == len(wc.step_details)

    def test_step_details_serialization(self, sample_exports):
        from src.coverage.workflow_coverage import analyze_workflow_coverage, WorkflowCoverage
        wc = analyze_workflow_coverage(sample_exports)
        d = wc.to_dict()
        for sd in d["step_details"]:
            assert "step_name" in sd
            assert "completion_rate" in sd
            assert isinstance(sd["completion_rate"], float)


class TestWorkflowCoverageFromFiles:
    """Test loading workflow coverage from JSON files on disk."""

    def test_load_from_directory(self, tmp_path, sample_exports):
        from src.coverage.workflow_coverage import load_workflow_coverage_from_exports
        # Write export files
        for i, exp in enumerate(sample_exports):
            with open(tmp_path / f"workflow_test_{i}.json", "w") as f:
                json.dump(exp, f)
        wc = load_workflow_coverage_from_exports(tmp_path)
        assert wc is not None
        assert wc.total_conversations > 0

    def test_no_workflow_files_returns_none(self, tmp_path):
        from src.coverage.workflow_coverage import load_workflow_coverage_from_exports
        wc = load_workflow_coverage_from_exports(tmp_path)
        assert wc is None

    def test_nonexistent_dir_returns_none(self):
        from src.coverage.workflow_coverage import load_workflow_coverage_from_exports
        wc = load_workflow_coverage_from_exports("/nonexistent/path")
        assert wc is None

    def test_malformed_json_skipped(self, tmp_path):
        from src.coverage.workflow_coverage import load_workflow_coverage_from_exports
        (tmp_path / "workflow_bad.json").write_text("not valid json")
        (tmp_path / "workflow_good.json").write_text(json.dumps(
            _sample_workflow_exports(1, 3, 1.0)[0]
        ))
        wc = load_workflow_coverage_from_exports(tmp_path)
        assert wc is not None
        assert wc.total_conversations == 3


class TestWorkflowCoverageIntegration:
    """Test integration with CoverageReport."""

    def _make_mock_coverage_report(self):
        """Create a mock CoverageReport-like object."""
        report = MagicMock()
        report.dimension_scores = {
            "persona_type": 0.85,
            "topic": 0.70,
            "scenario": 0.60,
            "judge": 0.90,
        }
        report.dimension_weights = {
            "persona_type": 0.30,
            "topic": 0.25,
            "scenario": 0.20,
            "judge": 0.25,
        }
        report.overall_coverage = 0.77
        report.grade = "B"
        report.gaps = ["Some existing gap"]
        report.recommendations = ["Some existing rec"]
        return report

    def test_inject_adds_workflow_dimension(self, sample_exports):
        from src.coverage.workflow_coverage import analyze_workflow_coverage, inject_workflow_coverage_into_report
        wc = analyze_workflow_coverage(sample_exports)
        report = self._make_mock_coverage_report()
        inject_workflow_coverage_into_report(report, wc)
        assert "workflow" in report.dimension_scores
        assert "workflow" in report.dimension_weights

    def test_inject_renormalizes_weights(self, sample_exports):
        from src.coverage.workflow_coverage import analyze_workflow_coverage, inject_workflow_coverage_into_report
        wc = analyze_workflow_coverage(sample_exports)
        report = self._make_mock_coverage_report()
        inject_workflow_coverage_into_report(report, wc, weight=0.20)
        total_weight = sum(report.dimension_weights.values())
        assert total_weight == pytest.approx(1.0, abs=0.01)

    def test_inject_workflow_weight_correct(self, sample_exports):
        from src.coverage.workflow_coverage import analyze_workflow_coverage, inject_workflow_coverage_into_report
        wc = analyze_workflow_coverage(sample_exports)
        report = self._make_mock_coverage_report()
        inject_workflow_coverage_into_report(report, wc, weight=0.25)
        assert report.dimension_weights["workflow"] == 0.25

    def test_inject_preserves_existing_gaps(self, sample_exports):
        from src.coverage.workflow_coverage import analyze_workflow_coverage, inject_workflow_coverage_into_report
        wc = analyze_workflow_coverage(sample_exports)
        report = self._make_mock_coverage_report()
        inject_workflow_coverage_into_report(report, wc)
        assert "Some existing gap" in report.gaps

    def test_inject_adds_workflow_gaps(self):
        from src.coverage.workflow_coverage import analyze_workflow_coverage, inject_workflow_coverage_into_report
        exports = [{
            "workflow": "WF", "domain": "test",
            "total_conversations": 3, "passed": 0, "failed": 3,
            "avg_score": 0.2, "critical_failures": 2,
            "results": [
                {"status": "failed", "step_results": [
                    {"step_name": "A", "step_id": "s1", "status": "completed", "required": True},
                    {"step_name": "B", "step_id": "s2", "status": "missed", "required": True},
                ]},
            ] * 3,
        }]
        wc = analyze_workflow_coverage(exports)
        report = self._make_mock_coverage_report()
        inject_workflow_coverage_into_report(report, wc)
        gap_text = " ".join(report.gaps)
        assert "never exercised" in gap_text or "critical" in gap_text.lower()

    def test_inject_updates_overall_coverage(self, sample_exports):
        from src.coverage.workflow_coverage import analyze_workflow_coverage, inject_workflow_coverage_into_report
        wc = analyze_workflow_coverage(sample_exports)
        report = self._make_mock_coverage_report()
        old_coverage = report.overall_coverage
        inject_workflow_coverage_into_report(report, wc)
        # Overall coverage should be recalculated
        assert isinstance(report.overall_coverage, float)

    def test_inject_adds_recommendations_for_low_coverage(self):
        from src.coverage.workflow_coverage import analyze_workflow_coverage, inject_workflow_coverage_into_report
        exports = [{
            "workflow": "WF", "domain": "test",
            "total_conversations": 3, "passed": 0, "failed": 3,
            "avg_score": 0.1, "critical_failures": 0,
            "results": [
                {"status": "failed", "step_results": [
                    {"step_name": "A", "step_id": "s1", "status": "missed", "required": True},
                ]},
            ] * 3,
        }]
        wc = analyze_workflow_coverage(exports)
        report = self._make_mock_coverage_report()
        inject_workflow_coverage_into_report(report, wc)
        rec_text = " ".join(report.recommendations)
        assert "workflow" in rec_text.lower() or "step" in rec_text.lower()


class TestWorkflowCoverageHTMLSection:
    """Test that workflow coverage appears in the coverage HTML section."""

    def test_coverage_html_dimensions_include_workflow(self, tmp_path, sample_exports):
        """When workflow data exists, coverage HTML should show workflow dimension."""
        from src.coverage.workflow_coverage import analyze_workflow_coverage, inject_workflow_coverage_into_report
        from src.coverage.models import CoverageReport, CoverageGrade

        # Build a real coverage report
        report = CoverageReport()
        report.dimension_scores = {"persona_type": 0.8, "topic": 0.7, "scenario": 0.6, "judge": 0.9}
        report.dimension_weights = {"persona_type": 0.3, "topic": 0.25, "scenario": 0.2, "judge": 0.25}
        report.overall_coverage = 0.75
        report.grade = CoverageGrade.B
        report.gaps = []
        report.recommendations = []

        # Inject workflow coverage
        wc = analyze_workflow_coverage(sample_exports)
        inject_workflow_coverage_into_report(report, wc)

        assert "workflow" in report.dimension_scores
        assert report.dimension_scores["workflow"] == pytest.approx(wc.score, abs=0.001)


class TestWorkflowCoverageEdgeCases:
    """Edge cases and boundary conditions."""

    def test_single_conversation_single_step(self):
        from src.coverage.workflow_coverage import analyze_workflow_coverage
        exports = [{
            "workflow": "Simple", "domain": "test",
            "total_conversations": 1, "passed": 1, "failed": 0,
            "avg_score": 1.0, "critical_failures": 0,
            "results": [{
                "status": "passed",
                "step_results": [{"step_name": "OnlyStep", "step_id": "s1", "status": "completed", "required": True}],
            }],
        }]
        wc = analyze_workflow_coverage(exports)
        assert wc.score == pytest.approx(1.0, abs=0.01)
        assert wc.steps_exercised == 1
        assert wc.steps_never_exercised == 0

    def test_all_steps_missed(self):
        from src.coverage.workflow_coverage import analyze_workflow_coverage
        exports = [{
            "workflow": "Bad", "domain": "test",
            "total_conversations": 3, "passed": 0, "failed": 3,
            "avg_score": 0.0, "critical_failures": 3,
            "results": [{
                "status": "failed",
                "step_results": [
                    {"step_name": "A", "step_id": "s1", "status": "missed", "required": True},
                    {"step_name": "B", "step_id": "s2", "status": "missed", "required": True},
                ],
            }] * 3,
        }]
        wc = analyze_workflow_coverage(exports)
        assert wc.step_coverage_score == 0.0
        assert wc.steps_never_exercised == 2
        assert len(wc.never_exercised_steps) == 2

    def test_results_missing_step_results_key(self):
        from src.coverage.workflow_coverage import analyze_workflow_coverage
        exports = [{
            "workflow": "WF", "domain": "test",
            "total_conversations": 2, "passed": 1, "failed": 1,
            "avg_score": 0.5, "critical_failures": 0,
            "results": [
                {"status": "passed", "completed_steps": ["A"], "missed_steps": []},
                {"status": "failed", "completed_steps": [], "missed_steps": ["A"]},
            ],
        }]
        wc = analyze_workflow_coverage(exports)
        assert wc.total_steps_defined > 0

    def test_required_steps_weighted_higher(self):
        from src.coverage.workflow_coverage import analyze_workflow_coverage
        # Required step completed, optional missed
        exports = [{
            "workflow": "WF", "domain": "test",
            "total_conversations": 1, "passed": 1, "failed": 0,
            "avg_score": 0.8, "critical_failures": 0,
            "results": [{
                "status": "passed",
                "step_results": [
                    {"step_name": "Required", "step_id": "s1", "status": "completed", "required": True},
                    {"step_name": "Optional", "step_id": "s2", "status": "missed", "required": False},
                ],
            }],
        }]
        wc = analyze_workflow_coverage(exports)
        # Required weight=2, optional weight=1. Score = (1.0*2 + 0.0*1) / 3 = 0.667
        assert wc.step_coverage_score == pytest.approx(2.0 / 3.0, abs=0.01)

    def test_domain_tracking(self):
        from src.coverage.workflow_coverage import analyze_workflow_coverage
        exports = [
            {"workflow": "WF1", "domain": "healthcare", "total_conversations": 1,
             "passed": 1, "failed": 0, "avg_score": 1.0, "critical_failures": 0, "results": []},
            {"workflow": "WF2", "domain": "finance", "total_conversations": 1,
             "passed": 1, "failed": 0, "avg_score": 1.0, "critical_failures": 0, "results": []},
        ]
        wc = analyze_workflow_coverage(exports)
        assert "healthcare" in wc.workflow_domains
        assert "finance" in wc.workflow_domains
