"""
Comparison Report Generator — HTML visual diff between two simulation runs.

Produces a self-contained HTML report with:
- Verdict banner (PASS/FAIL/WARNING/IMPROVED)
- Side-by-side metric cards with delta indicators
- Per-judge score comparison chart
- Failure pattern changes table
- CI/CD gate recommendation
"""

from __future__ import annotations

import html
import json
from pathlib import Path

from ai_simtest_engine.core.comparison_models import (
    ComparisonResult,
    DeltaDirection,
    FailurePatternDelta,
    JudgeComparison,
    MetricDelta,
    RegressionVerdict,
)


class ComparisonReportGenerator:
    """Generates HTML comparison reports."""

    def generate(self, result: ComparisonResult, output_path: str | Path,
                 workflow_comparison: list[dict] | None = None) -> Path:
        """Generate an HTML comparison report file."""
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        html_content = self._build_html(result, workflow_comparison)

        with open(output_path, "w") as f:
            f.write(html_content)

        return output_path

    def generate_json(self, result: ComparisonResult, output_path: str | Path) -> Path:
        """Generate a machine-readable JSON comparison report."""
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        with open(output_path, "w") as f:
            json.dump(result.model_dump(), f, indent=2, default=str)

        return output_path

    # ─── HTML Generation ────────────────────────────────────────

    def _build_html(self, result: ComparisonResult, workflow_comparison: list[dict] | None = None) -> str:
        s = result.summary
        wf_section = self._workflow_comparison_section(workflow_comparison) if workflow_comparison else ""
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>AI SimTest — Comparison Report</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4"></script>
<style>
{self._css()}
</style>
</head>
<body>
<div class="container">
    <header>
        <h1>🧪 AI SimTest — Comparison Report</h1>
        <p class="subtitle">{html.escape(s.baseline_name)} → {html.escape(s.current_name)}</p>
        <p class="date">Generated: {s.comparison_date[:19]}</p>
    </header>

    {self._verdict_banner(s.verdict, s.verdict_reasons, s.total_regressions, s.total_improvements)}

    <section class="metrics-grid">
        <h2>📊 Core Metrics</h2>
        <div class="cards">
            {self._metric_card("Pass Rate", s.pass_rate, fmt="pct")}
            {self._metric_card("Avg Score", s.average_score, fmt="score")}
            {self._metric_card("Critical Failures", s.critical_failures, fmt="int")}
            {self._metric_card("Conversations", s.total_conversations, fmt="int")}
            {self._metric_card("Total Turns", s.total_turns, fmt="int")}
        </div>
    </section>

    {self._judge_section(s.judge_comparisons)}
    {self._failure_pattern_section(s)}
    {wf_section}

    <section class="cicd-gate">
        <h2>🚦 CI/CD Gate</h2>
        <div class="gate-box gate-{s.verdict.value}">
            <span class="gate-icon">{"✅" if s.verdict in (RegressionVerdict.PASS, RegressionVerdict.IMPROVED) else "❌" if s.verdict == RegressionVerdict.FAIL else "⚠️"}</span>
            <span class="gate-text">
                {"DEPLOY SAFE — No regressions detected" if s.verdict == RegressionVerdict.PASS
                 else "DEPLOY SAFE — Improvements detected!" if s.verdict == RegressionVerdict.IMPROVED
                 else "BLOCK DEPLOY — Regressions detected" if s.verdict == RegressionVerdict.FAIL
                 else "REVIEW NEEDED — Minor regressions detected"}
            </span>
            <code>Exit code: {result.exit_code}</code>
        </div>
    </section>

    <footer>
        <p>Generated by <strong>AI SimTest</strong> v0.2.0 — Open-source AI simulation testing</p>
    </footer>
</div>

<script>
{self._chart_js(s.judge_comparisons)}
</script>
</body>
</html>"""

    def _verdict_banner(self, verdict: RegressionVerdict, reasons: list[str],
                        regressions: int, improvements: int) -> str:
        icons = {
            RegressionVerdict.PASS: "✅",
            RegressionVerdict.IMPROVED: "🎉",
            RegressionVerdict.WARNING: "⚠️",
            RegressionVerdict.FAIL: "🚨",
        }
        labels = {
            RegressionVerdict.PASS: "NO REGRESSIONS",
            RegressionVerdict.IMPROVED: "IMPROVED",
            RegressionVerdict.WARNING: "MINOR REGRESSIONS",
            RegressionVerdict.FAIL: "REGRESSIONS DETECTED",
        }

        reasons_html = ""
        if reasons:
            items = "".join(f"<li>{html.escape(r)}</li>" for r in reasons)
            reasons_html = f'<ul class="reasons">{items}</ul>'

        return f"""
    <section class="verdict verdict-{verdict.value}">
        <div class="verdict-header">
            <span class="verdict-icon">{icons[verdict]}</span>
            <span class="verdict-label">{labels[verdict]}</span>
        </div>
        <div class="verdict-stats">
            <span class="stat-reg">{regressions} regression{"s" if regressions != 1 else ""}</span>
            <span class="stat-imp">{improvements} improvement{"s" if improvements != 1 else ""}</span>
        </div>
        {reasons_html}
    </section>"""

    def _metric_card(self, label: str, metric: MetricDelta, fmt: str = "score") -> str:
        if fmt == "pct":
            b_display = f"{metric.baseline_value:.1%}"
            c_display = f"{metric.current_value:.1%}"
            d_display = f"{metric.delta:+.1%}"
        elif fmt == "int":
            b_display = f"{int(metric.baseline_value)}"
            c_display = f"{int(metric.current_value)}"
            d_display = f"{int(metric.delta):+d}"
        else:
            b_display = f"{metric.baseline_value:.3f}"
            c_display = f"{metric.current_value:.3f}"
            d_display = f"{metric.delta:+.3f}"

        css_class = {
            DeltaDirection.IMPROVED: "delta-improved",
            DeltaDirection.REGRESSED: "delta-regressed",
            DeltaDirection.UNCHANGED: "delta-unchanged",
        }[metric.direction]

        arrow = {"improved": "↑", "regressed": "↓", "unchanged": "→"}[metric.direction.value]

        return f"""
        <div class="card">
            <div class="card-label">{html.escape(label)}</div>
            <div class="card-values">
                <span class="baseline">{b_display}</span>
                <span class="arrow">→</span>
                <span class="current">{c_display}</span>
            </div>
            <div class="card-delta {css_class}">
                {arrow} {d_display} ({metric.delta_percent:+.1f}%)
            </div>
        </div>"""

    def _judge_section(self, judges: list[JudgeComparison]) -> str:
        if not judges:
            return ""

        rows = ""
        for j in judges:
            css = "delta-regressed" if j.is_regression else \
                  "delta-improved" if j.direction == DeltaDirection.IMPROVED else \
                  "delta-unchanged"
            arrow = "↓" if j.direction == DeltaDirection.REGRESSED else \
                    "↑" if j.direction == DeltaDirection.IMPROVED else "→"
            rows += f"""
            <tr>
                <td>{html.escape(j.judge_name)}</td>
                <td>{j.baseline_score:.3f}</td>
                <td>{j.current_score:.3f}</td>
                <td class="{css}">{arrow} {j.delta:+.3f} ({j.delta_percent:+.1f}%)</td>
            </tr>"""

        return f"""
    <section class="judges">
        <h2>⚖️ Judge Scores</h2>
        <div class="chart-container">
            <canvas id="judgeChart"></canvas>
        </div>
        <table>
            <thead><tr><th>Judge</th><th>Baseline</th><th>Current</th><th>Delta</th></tr></thead>
            <tbody>{rows}</tbody>
        </table>
    </section>"""

    def _failure_pattern_section(self, s) -> str:
        all_patterns = (
            s.new_failures + s.resolved_failures +
            s.persistent_failures + s.worsened_failures + s.improved_failures
        )
        if not all_patterns:
            return """
    <section class="failures">
        <h2>🔍 Failure Patterns</h2>
        <p class="empty">No failure patterns to compare.</p>
    </section>"""

        rows = ""
        for p in sorted(all_patterns, key=lambda x: x.status):
            status_badge = {
                "new": '<span class="badge badge-new">NEW</span>',
                "resolved": '<span class="badge badge-resolved">RESOLVED</span>',
                "persistent": '<span class="badge badge-persistent">PERSISTENT</span>',
                "worsened": '<span class="badge badge-worsened">WORSENED</span>',
                "improved": '<span class="badge badge-improved">IMPROVED</span>',
            }.get(p.status, p.status)

            rows += f"""
            <tr>
                <td>{html.escape(p.pattern_name)}</td>
                <td>{status_badge}</td>
                <td>{p.baseline_frequency}</td>
                <td>{p.current_frequency}</td>
                <td>{p.delta:+d}</td>
                <td><span class="severity severity-{p.severity}">{p.severity}</span></td>
            </tr>"""

        return f"""
    <section class="failures">
        <h2>🔍 Failure Patterns</h2>
        <div class="pattern-summary">
            <span class="ps-new">{len(s.new_failures)} new</span>
            <span class="ps-resolved">{len(s.resolved_failures)} resolved</span>
            <span class="ps-worsened">{len(s.worsened_failures)} worsened</span>
            <span class="ps-improved">{len(s.improved_failures)} improved</span>
            <span class="ps-persistent">{len(s.persistent_failures)} persistent</span>
        </div>
        <table>
            <thead><tr><th>Pattern</th><th>Status</th><th>Baseline</th><th>Current</th><th>Δ</th><th>Severity</th></tr></thead>
            <tbody>{rows}</tbody>
        </table>
    </section>"""

    def _chart_js(self, judges: list[JudgeComparison]) -> str:
        if not judges:
            return ""

        labels = json.dumps([j.judge_name for j in judges])
        baseline_data = json.dumps([j.baseline_score for j in judges])
        current_data = json.dumps([j.current_score for j in judges])

        return f"""
const ctx = document.getElementById('judgeChart').getContext('2d');
new Chart(ctx, {{
    type: 'bar',
    data: {{
        labels: {labels},
        datasets: [
            {{
                label: 'Baseline',
                data: {baseline_data},
                backgroundColor: 'rgba(107, 114, 128, 0.7)',
                borderColor: 'rgba(107, 114, 128, 1)',
                borderWidth: 1
            }},
            {{
                label: 'Current',
                data: {current_data},
                backgroundColor: 'rgba(59, 130, 246, 0.7)',
                borderColor: 'rgba(59, 130, 246, 1)',
                borderWidth: 1
            }}
        ]
    }},
    options: {{
        responsive: true,
        scales: {{
            y: {{
                beginAtZero: true,
                max: 1,
                grid: {{ color: 'rgba(255,255,255,0.1)' }},
                ticks: {{ color: '#9ca3af' }}
            }},
            x: {{
                grid: {{ display: false }},
                ticks: {{ color: '#9ca3af' }}
            }}
        }},
        plugins: {{
            legend: {{ labels: {{ color: '#e5e7eb' }} }}
        }}
    }}
}});"""

    def _workflow_comparison_section(self, wf_data: list[dict]) -> str:
        """Build HTML section comparing workflow results between runs."""
        if not wf_data:
            return ""

        rows = ""
        for wf in wf_data:
            name = html.escape(wf.get("name", "Unknown"))
            b_score = wf.get("baseline_score", 0)
            c_score = wf.get("current_score", 0)
            delta = c_score - b_score
            b_pass = wf.get("baseline_pass", "—")
            c_pass = wf.get("current_pass", "—")
            c_crit = wf.get("current_critical", "—")
            status = wf.get("status", "")  # NEW, REMOVED, or ""

            if status == "NEW":
                delta_html = '<span class="badge badge-new">NEW</span>'
            elif status == "REMOVED":
                delta_html = '<span class="badge badge-resolved">REMOVED</span>'
            else:
                css = "delta-improved" if delta > 0.01 else "delta-regressed" if delta < -0.01 else "delta-unchanged"
                arrow = "↑" if delta > 0.01 else "↓" if delta < -0.01 else "→"
                delta_html = f'<span class="{css}">{arrow} {delta:+.3f}</span>'

            rows += f"""
            <tr>
                <td>{name}</td>
                <td>{"—" if status == "NEW" else f"{b_score:.3f}"}</td>
                <td>{"—" if status == "REMOVED" else f"{c_score:.3f}"}</td>
                <td>{delta_html}</td>
                <td>{b_pass}</td>
                <td>{c_pass}</td>
                <td>{c_crit}</td>
            </tr>"""

        return f"""
    <section class="workflows">
        <h2>&#x1f527; Workflow Judge Comparison</h2>
        <table>
            <thead><tr><th>Workflow</th><th>Baseline</th><th>Current</th><th>Delta</th><th>Base Pass</th><th>Curr Pass</th><th>Critical</th></tr></thead>
            <tbody>{rows}</tbody>
        </table>
    </section>"""

    def _css(self) -> str:
        return """
* { margin: 0; padding: 0; box-sizing: border-box; }
body { background: #0f172a; color: #e2e8f0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; }
.container { max-width: 960px; margin: 0 auto; padding: 2rem; }
header { text-align: center; margin-bottom: 2rem; }
header h1 { font-size: 1.8rem; color: #f8fafc; }
.subtitle { color: #94a3b8; margin-top: 0.5rem; font-size: 1.1rem; }
.date { color: #64748b; font-size: 0.85rem; margin-top: 0.25rem; }
h2 { color: #f1f5f9; margin-bottom: 1rem; font-size: 1.3rem; }
section { margin-bottom: 2rem; }

/* Verdict */
.verdict { border-radius: 12px; padding: 1.5rem; text-align: center; }
.verdict-pass { background: linear-gradient(135deg, #065f46, #064e3b); border: 1px solid #10b981; }
.verdict-improved { background: linear-gradient(135deg, #1e3a5f, #172554); border: 1px solid #3b82f6; }
.verdict-warning { background: linear-gradient(135deg, #713f12, #78350f); border: 1px solid #f59e0b; }
.verdict-fail { background: linear-gradient(135deg, #7f1d1d, #991b1b); border: 1px solid #ef4444; }
.verdict-header { display: flex; align-items: center; justify-content: center; gap: 0.75rem; }
.verdict-icon { font-size: 2rem; }
.verdict-label { font-size: 1.5rem; font-weight: 700; }
.verdict-stats { margin-top: 0.75rem; display: flex; gap: 1.5rem; justify-content: center; }
.stat-reg { color: #fca5a5; }
.stat-imp { color: #86efac; }
.reasons { list-style: none; margin-top: 1rem; text-align: left; max-width: 600px; margin-left: auto; margin-right: auto; }
.reasons li { padding: 0.25rem 0; color: #fde68a; font-size: 0.9rem; }
.reasons li::before { content: "• "; color: #f59e0b; }

/* Metric Cards */
.cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(170px, 1fr)); gap: 1rem; }
.card { background: #1e293b; border-radius: 10px; padding: 1rem; text-align: center; border: 1px solid #334155; }
.card-label { color: #94a3b8; font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.05em; }
.card-values { margin: 0.5rem 0; font-size: 1.1rem; display: flex; align-items: center; justify-content: center; gap: 0.5rem; }
.baseline { color: #9ca3af; }
.arrow { color: #64748b; }
.current { color: #f8fafc; font-weight: 600; }
.card-delta { font-size: 0.85rem; font-weight: 600; }
.delta-improved { color: #34d399; }
.delta-regressed { color: #f87171; }
.delta-unchanged { color: #94a3b8; }

/* Judge Chart */
.chart-container { max-width: 600px; margin: 0 auto 1.5rem; }

/* Tables */
table { width: 100%; border-collapse: collapse; background: #1e293b; border-radius: 8px; overflow: hidden; }
th { background: #334155; color: #e2e8f0; padding: 0.75rem; text-align: left; font-size: 0.85rem; text-transform: uppercase; }
td { padding: 0.75rem; border-top: 1px solid #334155; font-size: 0.9rem; }

/* Badges */
.badge { padding: 0.2rem 0.6rem; border-radius: 4px; font-size: 0.75rem; font-weight: 600; }
.badge-new { background: #dc2626; color: #fff; }
.badge-resolved { background: #16a34a; color: #fff; }
.badge-persistent { background: #64748b; color: #fff; }
.badge-worsened { background: #ea580c; color: #fff; }
.badge-improved { background: #2563eb; color: #fff; }

.severity { padding: 0.15rem 0.4rem; border-radius: 3px; font-size: 0.75rem; }
.severity-critical { background: #7f1d1d; color: #fca5a5; }
.severity-high { background: #78350f; color: #fde68a; }
.severity-medium { background: #1e3a5f; color: #93c5fd; }
.severity-low { background: #064e3b; color: #86efac; }

.pattern-summary { display: flex; gap: 1rem; margin-bottom: 1rem; flex-wrap: wrap; }
.pattern-summary span { font-size: 0.85rem; font-weight: 600; }
.ps-new { color: #f87171; }
.ps-resolved { color: #34d399; }
.ps-worsened { color: #fb923c; }
.ps-improved { color: #60a5fa; }
.ps-persistent { color: #94a3b8; }

.empty { color: #64748b; font-style: italic; }

/* CI/CD Gate */
.gate-box { display: flex; align-items: center; gap: 1rem; padding: 1.25rem; border-radius: 10px; }
.gate-pass, .gate-improved { background: #064e3b; border: 1px solid #10b981; }
.gate-warning { background: #78350f; border: 1px solid #f59e0b; }
.gate-fail { background: #7f1d1d; border: 1px solid #ef4444; }
.gate-icon { font-size: 1.5rem; }
.gate-text { flex: 1; font-weight: 600; font-size: 1.05rem; }
.gate-box code { background: #0f172a; padding: 0.3rem 0.6rem; border-radius: 4px; font-size: 0.85rem; color: #94a3b8; }

footer { text-align: center; color: #475569; padding-top: 2rem; border-top: 1px solid #1e293b; font-size: 0.85rem; }
"""