"""
Adaptive Expansion Models — Data structures for failure-driven test expansion.

P3 #13: When a failure is found, auto-generate variations to confirm
reproducibility and produce a minimal reproducible conversation.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class SignalSeverity(str, Enum):
    """Severity of a failure signal — determines expansion priority."""
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class ReproducibilityVerdict(str, Enum):
    """Whether a failure is confirmed reproducible."""
    CONFIRMED = "confirmed"       # >=60% variants reproduced
    LIKELY = "likely"             # 40-59% reproduced
    FLUKE = "fluke"               # <40% reproduced
    INCONCLUSIVE = "inconclusive" # Not enough data


class VariantStrategy(str, Enum):
    """Strategy used to generate a variant."""
    REPHRASE = "rephrase"           # Same intent, different wording
    PERSONA_SHIFT = "persona_shift" # Different user type asking same thing
    ADVERSARIAL = "adversarial"     # Deliberate attempt to trigger failure
    INDIRECT = "indirect"           # Approach the topic from an oblique angle
    EDGE_CASE = "edge_case"         # Boundary condition or unusual input


@dataclass
class FailureSignal:
    """
    A structured representation of a failure detected during simulation.

    Extracted from judged conversations — captures what went wrong,
    which judge flagged it, and the conversation context around it.
    """
    signal_id: str
    judge_name: str                     # grounding, safety, quality, relevance, workflow
    severity: SignalSeverity
    score: float                        # Original judge score (0-1)
    message: str                        # Judge's failure message
    conversation_id: str                # Source conversation
    persona_name: str                   # Persona that triggered it
    persona_type: str                   # standard, edge_case, adversarial
    turn_index: int                     # Which turn failed
    user_message: str                   # The user message that preceded the failure
    bot_response: str                   # The bot response that failed
    conversation_context: list[dict]    # Preceding turns for context
    evidence: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "signal_id": self.signal_id,
            "judge_name": self.judge_name,
            "severity": self.severity.value,
            "score": self.score,
            "message": self.message,
            "conversation_id": self.conversation_id,
            "persona_name": self.persona_name,
            "persona_type": self.persona_type,
            "turn_index": self.turn_index,
            "user_message": self.user_message,
            "bot_response": self.bot_response,
            "evidence": self.evidence,
        }


@dataclass
class ExpansionVariant:
    """
    A variant conversation designed to probe a specific failure.

    Generated by LLM to test the same vulnerability from a different angle.
    """
    variant_id: str
    signal_id: str                  # Which failure signal this probes
    strategy: VariantStrategy       # How this variant approaches the failure
    persona_name: str               # Name for the variant persona
    persona_description: str        # Brief description of the variant persona
    system_prompt: str              # Full system prompt for the variant persona
    opening_message: str            # First user message to send
    rationale: str                  # Why this variant should trigger the same failure
    max_turns: int = 10             # How many turns to run

    def to_dict(self) -> dict[str, Any]:
        return {
            "variant_id": self.variant_id,
            "signal_id": self.signal_id,
            "strategy": self.strategy.value,
            "persona_name": self.persona_name,
            "persona_description": self.persona_description,
            "opening_message": self.opening_message,
            "rationale": self.rationale,
            "max_turns": self.max_turns,
        }


@dataclass
class VariantResult:
    """Result of running a single variant conversation against the bot."""
    variant: ExpansionVariant
    reproduced: bool                # Did the same failure type recur?
    matching_judge: str             # Which judge flagged the reproduced failure
    matching_score: float           # Score from the matching judge
    matching_message: str           # Judge message
    conversation_turns: int         # How many turns the conversation ran
    all_judgments: list[dict] = field(default_factory=list)  # All judge results per turn
    error: str | None = None        # If variant execution failed

    def to_dict(self) -> dict[str, Any]:
        return {
            "variant_id": self.variant.variant_id,
            "signal_id": self.variant.signal_id,
            "strategy": self.variant.strategy.value,
            "reproduced": self.reproduced,
            "matching_judge": self.matching_judge,
            "matching_score": self.matching_score,
            "matching_message": self.matching_message,
            "conversation_turns": self.conversation_turns,
            "error": self.error,
        }


@dataclass
class SignalExpansionResult:
    """Complete expansion result for a single failure signal."""
    signal: FailureSignal
    variants: list[ExpansionVariant]
    results: list[VariantResult]
    reproducibility_score: float        # 0-1: fraction of variants that reproduced
    verdict: ReproducibilityVerdict
    minimal_repro: VariantResult | None  # Shortest conversation that reproduced
    total_variants: int
    reproduced_count: int

    def to_dict(self) -> dict[str, Any]:
        return {
            "signal": self.signal.to_dict(),
            "reproducibility_score": round(self.reproducibility_score, 3),
            "verdict": self.verdict.value,
            "total_variants": self.total_variants,
            "reproduced_count": self.reproduced_count,
            "minimal_repro_turns": self.minimal_repro.conversation_turns if self.minimal_repro else None,
            "variant_results": [r.to_dict() for r in self.results],
        }


@dataclass
class ExpansionReport:
    """Complete report from adaptive expansion across all failure signals."""
    total_signals_found: int
    signals_expanded: int
    total_variants_run: int
    confirmed_bugs: list[SignalExpansionResult]   # verdict = CONFIRMED
    likely_bugs: list[SignalExpansionResult]       # verdict = LIKELY
    flukes: list[SignalExpansionResult]            # verdict = FLUKE
    errors: list[str]                             # Any execution errors
    execution_time_seconds: float

    @property
    def confirmed_count(self) -> int:
        return len(self.confirmed_bugs)

    @property
    def likely_count(self) -> int:
        return len(self.likely_bugs)

    @property
    def fluke_count(self) -> int:
        return len(self.flukes)

    @property
    def has_confirmed_bugs(self) -> bool:
        return self.confirmed_count > 0

    def to_dict(self) -> dict[str, Any]:
        return {
            "total_signals_found": self.total_signals_found,
            "signals_expanded": self.signals_expanded,
            "total_variants_run": self.total_variants_run,
            "confirmed_bugs": [r.to_dict() for r in self.confirmed_bugs],
            "likely_bugs": [r.to_dict() for r in self.likely_bugs],
            "flukes": [r.to_dict() for r in self.flukes],
            "confirmed_count": self.confirmed_count,
            "likely_count": self.likely_count,
            "fluke_count": self.fluke_count,
            "errors": self.errors,
            "execution_time_seconds": round(self.execution_time_seconds, 2),
        }

    def to_summary_dict(self) -> dict[str, Any]:
        """Compact summary for CI/CD pipelines."""
        return {
            "signals_found": self.total_signals_found,
            "signals_expanded": self.signals_expanded,
            "variants_run": self.total_variants_run,
            "confirmed_bugs": self.confirmed_count,
            "likely_bugs": self.likely_count,
            "flukes": self.fluke_count,
            "has_confirmed_bugs": self.has_confirmed_bugs,
            "execution_time_seconds": round(self.execution_time_seconds, 2),
        }


@dataclass
class AdaptiveExpansionConfig:
    """Configuration for adaptive expansion."""
    enabled: bool = True
    max_signals: int = 5                # Max failure signals to expand
    variants_per_signal: int = 5        # Variants to generate per signal
    max_turns_per_variant: int = 10     # Max turns per variant conversation
    min_severity: SignalSeverity = SignalSeverity.MEDIUM  # Minimum severity to expand
    reproducibility_threshold: float = 0.6  # Threshold for CONFIRMED verdict
    likely_threshold: float = 0.4       # Threshold for LIKELY verdict
    max_parallel_variants: int = 3      # Parallel variant executions
    include_workflow_signals: bool = True  # Also expand workflow judge failures

    def validate(self) -> list[str]:
        """Validate config, return list of issues."""
        issues = []
        if self.max_signals < 1:
            issues.append("max_signals must be >= 1")
        if self.variants_per_signal < 1:
            issues.append("variants_per_signal must be >= 1")
        if self.max_turns_per_variant < 3:
            issues.append("max_turns_per_variant must be >= 3")
        if not 0 < self.reproducibility_threshold <= 1:
            issues.append("reproducibility_threshold must be between 0 and 1")
        if self.likely_threshold >= self.reproducibility_threshold:
            issues.append("likely_threshold must be less than reproducibility_threshold")
        return issues
