"""
Multi-Model Comparison — HTML Dashboard (Phase 5).

Enterprise-grade decision dashboard that consumes MultiCompareReport
and renders a self-contained, dark-themed HTML report with:

- Sticky summary header with winner + gate + alerts
- Confidence badges per dimension (High/Medium/Low)
- Strict/Exploratory mode visibility
- Coverage parity impact visualization
- Normalized heatmap with inverted-metric handling
- Interactive sorting and filtering (JS)
- Champion vs Challenger evidence cards
- Cost vs Quality frontier scatter chart
- Persona-based leaderboard (product differentiator)
- Decision profile explanation panel
- Deployment recommendation panel
- Export (Copy JSON / CSV) buttons
- Future drill-down hooks (placeholder anchors)

Review points addressed: #1–#17 from enterprise review.
"""

from __future__ import annotations

import html
import json
from pathlib import Path
from typing import Any

from src.multi_compare.models import (
    ComparisonMatrix,
    ComparisonMode,
    CostEfficiency,
    CostGovernance,
    CoverageParityReport,
    DiffExplanation,
    Dimension,
    DimensionScore,
    FailureForensic,
    GateCheck,
    GateResult,
    GateVerdict,
    INVERTED_DIMENSIONS,
    ModelRanking,
    MultiCompareReport,
    SliceResult,
)


# ─────────────────────────────────────────────────────────────
# Public API
# ─────────────────────────────────────────────────────────────

class MultiCompareDashboard:
    """Generates self-contained HTML dashboard for multi-model comparison."""

    def export(
        self,
        report: MultiCompareReport,
        output_path: str | Path,
    ) -> Path:
        """Render and write HTML dashboard to disk."""
        path = Path(output_path)
        content = self.render(report)
        path.write_text(content, encoding="utf-8")
        return path

    def render(self, report: MultiCompareReport) -> str:
        """Render complete HTML string."""
        matrix = report.comparison_matrix
        rankings = matrix.rankings
        mode = _detect_mode(report)
        champion_id = matrix.champion_id
        parity_status = _compute_parity_status(matrix.coverage_parity)
        has_low_confidence = _has_low_confidence(rankings)
        has_summary_only = True  # Phase 4 uses summary-only evidence

        # Prepare report JSON for export
        report_json = _safe_json_serialize(report)

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>AI SimTest — Multi-Model Comparison</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.min.js"></script>
<style>
{_get_css()}
</style>
</head>
<body>

{self._render_sticky_header(report, parity_status)}

{self._render_header(report, mode, parity_status, has_low_confidence, has_summary_only)}

{self._render_global_warnings(report, parity_status, has_low_confidence, has_summary_only)}

{self._render_scorecard(rankings, champion_id, matrix.overall_winner, parity_status, mode)}

{self._render_profile_panel(report)}

{self._render_heatmap(rankings, champion_id)}

{self._render_charts(rankings, report.cost_analysis)}

{self._render_diffs(matrix.diff_explanations, matrix.champion_id)}

{self._render_leaderboard(matrix.slice_analysis)}

{self._render_cost_table(report.cost_analysis, report.cost_governance)}

{self._render_forensics(report.forensics)}

{self._render_parity(matrix.coverage_parity, parity_status)}

{self._render_deployment_panel(rankings, report.cost_analysis)}

{self._render_recommendations(report.recommendations)}

{self._render_gates(report.gate_result)}

<footer>
  Generated by <strong>AI SimTest</strong> v1.3.0 · Open-source AI Simulation Testing Platform
  <!-- FUTURE: per-conversation drill-down viewer -->
</footer>

<script>
{_get_dashboard_js(rankings, report.cost_analysis, report_json)}
</script>

</body>
</html>"""

    # ─────────────────────────────────────────────────────────
    # Section Renderers
    # ─────────────────────────────────────────────────────────

    def _render_sticky_header(
        self,
        report: MultiCompareReport,
        parity_status: str,
    ) -> str:
        """Sticky summary bar visible while scrolling (Review #12)."""
        matrix = report.comparison_matrix
        gate = report.gate_result
        winner = matrix.overall_winner

        gate_cls = "pass" if gate.verdict == GateVerdict.PASS else "fail"
        gate_text = "PASS" if gate.verdict == GateVerdict.PASS else "FAIL"

        winner_text = _esc(winner) if winner else "No clear winner"
        winner_cls = "pass" if winner else "dim"

        parity_cls = _parity_css_class(parity_status)

        alerts = []
        if parity_status == "INVALID":
            alerts.append("⚠ Invalid parity")
        if _has_low_confidence(matrix.rankings):
            alerts.append("⚠ Low confidence")
        if not gate.passed:
            alerts.append("⚠ Gate failed")
        alert_html = " · ".join(alerts) if alerts else ""

        return f"""
<div class="sticky-header">
  <span class="sh-label">Winner:</span>
  <span class="sh-value {winner_cls}">{winner_text}</span>
  <span class="sh-divider">|</span>
  <span class="sh-label">Gate:</span>
  <span class="sh-badge {gate_cls}">{gate_text}</span>
  <span class="sh-divider">|</span>
  <span class="sh-label">Parity:</span>
  <span class="sh-badge {parity_cls}">{parity_status}</span>
  {f'<span class="sh-divider">|</span><span class="sh-alert">{alert_html}</span>' if alert_html else ''}
</div>"""

    def _render_header(
        self,
        report: MultiCompareReport,
        mode: str,
        parity_status: str,
        has_low_confidence: bool,
        has_summary_only: bool,
    ) -> str:
        """Main header with run identity and mode badges (Review #6)."""
        matrix = report.comparison_matrix

        comp_mode = "CHAMPION vs CHALLENGER" if matrix.champion_id else "HEAD-TO-HEAD"
        mode_cls = "badge-strict" if mode == "STRICT" else "badge-exploratory"
        mode_label = mode

        profile = matrix.profile_applied or "balanced"

        manifest_html = ""
        if report.run_manifest_id:
            short_id = report.run_manifest_id[:12]
            manifest_html = f'<span class="header-dim">Manifest: {_esc(short_id)}…</span>'

        return f"""
<header>
  <div class="header-top">
    <h1>AI SimTest — Multi-Model Comparison</h1>
    <span class="header-badge">v1.3.0</span>
  </div>
  <div class="header-meta">
    <span class="header-sub">{_esc(report.config_name)} · {_esc(report.timestamp[:19])}Z</span>
    {manifest_html}
  </div>
  <div class="header-badges">
    <span class="mode-badge {mode_cls}">{mode_label}</span>
    <span class="comp-badge">{comp_mode}</span>
    <span class="profile-badge">Profile: {_esc(profile)}</span>
    <span class="model-count">{len(report.models_compared)} models · {report.shared_persona_count} personas</span>
  </div>
</header>"""

    def _render_global_warnings(
        self,
        report: MultiCompareReport,
        parity_status: str,
        has_low_confidence: bool,
        has_summary_only: bool,
    ) -> str:
        """Global warning banners for confidence/parity issues (Review #1, #2)."""
        warnings = []

        if has_low_confidence:
            warnings.append(
                "⚠️ <strong>Low Confidence:</strong> Some dimensions are based on "
                "fewer than 5 conversations. Rankings may not be reliable. "
                "Increase persona count for stronger results."
            )

        if has_summary_only:
            warnings.append(
                "ℹ️ <strong>Evidence Level:</strong> Analysis is based on "
                "summary-level metrics only. Conversation-level evidence "
                "will provide stronger verdicts in future versions."
            )

        if parity_status == "INVALID":
            warnings.append(
                "🚫 <strong>Invalid Parity:</strong> One or more models completed "
                "fewer than 50% of test cases. Rankings may be unreliable. "
                "Overall winner determination is blocked in strict mode."
            )
        elif parity_status == "DEGRADED":
            warnings.append(
                "⚠️ <strong>Degraded Parity:</strong> One or more models completed "
                "fewer than 85% of test cases. Rankings are indicative but "
                "should be verified with a full run."
            )

        if not warnings:
            return ""

        items = "\n".join(
            f'  <div class="global-warning">{w}</div>' for w in warnings
        )
        return f"""
<div class="warning-banner">
{items}
</div>"""

    def _render_scorecard(
        self,
        rankings: list[ModelRanking],
        champion_id: str | None,
        overall_winner: str | None,
        parity_status: str,
        mode: str,
    ) -> str:
        """Model scorecard row (Review #2, #3)."""
        cards = []
        for r in sorted(rankings, key=lambda x: x.overall_rank):
            is_champion = (r.model_id == champion_id)
            is_winner = (r.model_id == overall_winner)
            score_cls = _score_class(r.overall_score)

            # Rank display with tie support (Review #3)
            rank_text = f"#{r.overall_rank}"
            rank_extra = ""
            if _is_tied_rank(r, rankings):
                rank_text = f"T{r.overall_rank}"
                rank_extra = ' <span class="rank-tied">≈ Tied</span>'

            # Confidence-adjusted rank (Review #3)
            if _has_low_confidence_model(r):
                rank_extra += ' <span class="rank-unconfirmed">unconfirmed</span>'

            # Deployment status
            deploy_icon = "✅" if r.deployment_ready else "❌"
            deploy_tip = ""
            if not r.deployment_ready:
                deploy_tip = _esc("; ".join(r.deployment_blockers))

            # Card classes
            card_cls = "scorecard"
            if is_champion:
                card_cls += " champion-card"
            if is_winner:
                card_cls += " winner-card"

            # Parity warning badge (Review #2)
            parity_badge = ""
            if parity_status in ("DEGRADED", "INVALID"):
                parity_badge = f' <span class="parity-badge parity-{parity_status.lower()}">⚠</span>'

            cards.append(f"""
    <div class="{card_cls}" id="drilldown-{_esc(r.model_id)}">
      <div class="sc-rank {score_cls}">{rank_text}{rank_extra}</div>
      <div class="sc-name">{_esc(r.model_name)}{parity_badge}</div>
      <div class="sc-id">{_esc(r.model_id)}</div>
      <div class="sc-score {score_cls}">{r.overall_score:.3f}</div>
      <div class="sc-deploy" title="{deploy_tip}">{deploy_icon}</div>
      {f'<div class="sc-champion-tag">CHAMPION</div>' if is_champion else ''}
      {f'<div class="sc-winner-tag">WINNER</div>' if is_winner else ''}
    </div>""")

        # No clear winner display (Review #3)
        winner_section = ""
        if not overall_winner:
            reason = "Invalid parity — winner blocked" if (
                parity_status == "INVALID" and mode == "STRICT"
            ) else "No statistically clear winner"
            winner_section = f"""
  <div class="no-winner-banner">
    <span class="nw-icon">⚖️</span>
    <span class="nw-text">{reason}</span>
  </div>"""

        return f"""
<section class="section">
  <h2>🏆 Model Rankings</h2>
  {winner_section}
  <div class="scorecard-grid">
    {"".join(cards)}
  </div>
</section>"""

    def _render_profile_panel(self, report: MultiCompareReport) -> str:
        """Decision profile explanation panel (Review #10)."""
        matrix = report.comparison_matrix
        profile_name = matrix.profile_applied or "balanced"
        profiles_applied = report.decision_profiles_applied or [profile_name]

        # Extract weight data from built-in profiles
        weight_data = _get_profile_weights(profile_name)
        if not weight_data:
            return ""

        # Build weight bars
        bars = []
        for dim_name, weight in sorted(weight_data.items(), key=lambda x: -x[1]):
            pct = weight * 100
            label = dim_name.replace("_", " ").title()
            bars.append(
                f'<div class="pw-row">'
                f'<span class="pw-label">{_esc(label)}</span>'
                f'<div class="pw-bar-bg"><div class="pw-bar" style="width:{pct:.0f}%"></div></div>'
                f'<span class="pw-pct">{pct:.0f}%</span>'
                f'</div>'
            )

        influence_note = _profile_influence_note(profile_name, matrix)

        return f"""
<section class="section profile-panel">
  <h2>⚖️ Decision Profile: {_esc(profile_name.replace('_', ' ').title())}</h2>
  <p class="profile-desc">{_esc(_profile_description(profile_name))}</p>
  <div class="profile-weights">
    {"".join(bars)}
  </div>
  {f'<div class="profile-influence">{_esc(influence_note)}</div>' if influence_note else ''}
</section>"""

    def _render_heatmap(
        self,
        rankings: list[ModelRanking],
        champion_id: str | None,
    ) -> str:
        """
        Dimension heatmap table with normalization (Review #1, #4, #8).

        Raw values shown as text, normalized colors applied.
        Inverted dimensions marked with ↓.
        Confidence badges per cell.
        Evidence transparency in tooltips.
        """
        if not rankings:
            return ""

        # Collect all dimensions
        all_dims = _collect_dimensions(rankings)
        if not all_dims:
            return ""

        # Compute normalization ranges per dimension
        norm_ranges = _compute_normalization_ranges(rankings, all_dims)

        # Header row
        dim_headers = []
        for dim in all_dims:
            is_inv = dim in INVERTED_DIMENSIONS
            inv_mark = ' <span class="inv-mark">↓</span>' if is_inv else ""
            label = dim.value.replace("_", " ").title()
            dim_headers.append(f'<th class="hm-dim-header">{label}{inv_mark}</th>')

        # Data rows
        rows = []
        for r in sorted(rankings, key=lambda x: x.overall_rank):
            is_champ = (r.model_id == champion_id)
            row_cls = "hm-champion-row" if is_champ else ""

            cells = []
            dim_scores = {ds.dimension: ds for ds in r.dimensions}
            for dim in all_dims:
                ds = dim_scores.get(dim)
                if not ds:
                    cells.append('<td class="hm-cell hm-na">—</td>')
                    continue

                raw = ds.score
                is_inv = dim in INVERTED_DIMENSIONS
                norm = _normalize_score(raw, dim, norm_ranges, is_inv)
                bg = _heatmap_color(norm)

                # Delta from champion (Review #5)
                delta_html = ""
                if ds.delta_from_champion is not None:
                    delta = ds.delta_from_champion
                    d_cls = "delta-pos" if delta > 0.005 else "delta-neg" if delta < -0.005 else "delta-zero"
                    d_sign = "+" if delta > 0 else ""
                    delta_html = f'<div class="hm-delta {d_cls}">{d_sign}{delta:.3f}</div>'

                # Winner star
                star = ' <span class="hm-star">★</span>' if ds.is_winner else ""

                # Confidence badge (Review #1)
                conf = _dimension_confidence(ds)
                conf_cls = f"conf-{conf.lower()}"
                conf_badge = f'<span class="conf-badge {conf_cls}">{conf[0]}</span>'

                # Statistical verdict badge
                verdict_html = ""
                if ds.statistical_verdict:
                    v = ds.statistical_verdict
                    v_label = v.verdict.value.replace("_", " ").title()[:12]
                    verdict_html = f'<div class="hm-verdict">{_esc(v_label)}</div>'

                # Format raw value
                raw_text = _format_raw_value(raw, dim)

                # Tooltip with evidence (Review #8)
                tooltip = _evidence_tooltip(ds)

                cells.append(
                    f'<td class="hm-cell" style="background:{bg};" title="{_esc(tooltip)}">'
                    f'<div class="hm-raw">{raw_text}{star}</div>'
                    f'{delta_html}'
                    f'<div class="hm-meta">{conf_badge} {verdict_html}</div>'
                    f'</td>'
                )

            rows.append(
                f'<tr class="{row_cls}">'
                f'<td class="hm-model">{_esc(r.model_name)}</td>'
                f'{"".join(cells)}'
                f'</tr>'
            )

        return f"""
<section class="section">
  <h2>📊 Dimension Heatmap</h2>
  <p class="section-hint">Cells colored by normalized score. Raw values shown as text. ↓ = lower is better. Confidence: <span class="conf-badge conf-high">H</span>igh <span class="conf-badge conf-medium">M</span>edium <span class="conf-badge conf-low">L</span>ow</p>
  <div class="table-wrapper">
    <table class="heatmap-table sortable" id="heatmapTable">
      <thead>
        <tr>
          <th class="hm-model-header">Model</th>
          {"".join(dim_headers)}
        </tr>
      </thead>
      <tbody>
        {"".join(rows)}
      </tbody>
    </table>
  </div>
</section>"""

    def _render_charts(
        self,
        rankings: list[ModelRanking],
        cost_analysis: list[CostEfficiency],
    ) -> str:
        """Charts row: grouped bar, radar, cost vs quality scatter (Review #14)."""
        return f"""
<section class="section">
  <h2>📈 Visual Analysis</h2>
  <div class="charts-row">
    <div class="chart-card">
      <h3>Dimension Comparison</h3>
      <canvas id="dimensionBarChart" height="280"></canvas>
    </div>
    <div class="chart-card">
      <h3>Model Profiles (Radar)</h3>
      <canvas id="radarChart" height="280"></canvas>
    </div>
    <div class="chart-card">
      <h3>Cost vs Quality Frontier</h3>
      <canvas id="costQualityChart" height="280"></canvas>
    </div>
  </div>
</section>"""

    def _render_diffs(
        self,
        diff_explanations: list[DiffExplanation],
        champion_id: str | None,
    ) -> str:
        """Champion vs Challenger evidence cards (Review #5, #16)."""
        if not diff_explanations or not champion_id:
            return ""

        cards = []
        for diff in diff_explanations:
            wins_html = _render_diff_list(diff.wins, "✅", "win")
            losses_html = _render_diff_list(diff.losses, "❌", "loss")
            neutral_html = _render_diff_list(diff.neutral, "➖", "neutral")

            # Evidence count (Review #5)
            evidence_count = len(diff.wins) + len(diff.losses) + len(diff.neutral)

            # Top 3 improvements and regressions (Review #5)
            top_improvements = diff.wins[:3]
            top_regressions = diff.losses[:3]

            top_imp_html = ""
            if top_improvements:
                items = "".join(f'<li class="evidence-item ev-win">{_esc(w)}</li>' for w in top_improvements)
                top_imp_html = f'<div class="top-evidence"><strong>Top improvements:</strong><ul>{items}</ul></div>'

            top_reg_html = ""
            if top_regressions:
                items = "".join(f'<li class="evidence-item ev-loss">{_esc(l)}</li>' for l in top_regressions)
                top_reg_html = f'<div class="top-evidence"><strong>Top regressions:</strong><ul>{items}</ul></div>'

            # Uncertainty note (Review #16)
            uncertainty = ""
            if evidence_count < 5:
                uncertainty = '<div class="uncertainty-note">⚠ Limited evidence — interpret with caution</div>'

            cards.append(f"""
    <div class="diff-card">
      <div class="diff-header" onclick="this.parentElement.classList.toggle('expanded')">
        <span class="diff-title">{_esc(diff.challenger_id)} vs {_esc(diff.vs_champion_id)}</span>
        <span class="diff-summary">{_esc(diff.summary)}</span>
        <span class="diff-evidence-count">{evidence_count} dimensions</span>
        <span class="diff-expand">▶</span>
      </div>
      <div class="diff-body">
        {top_imp_html}
        {top_reg_html}
        <div class="diff-lists">
          <div class="diff-col">{wins_html}</div>
          <div class="diff-col">{losses_html}</div>
          <div class="diff-col">{neutral_html}</div>
        </div>
        {uncertainty}
        <!-- FUTURE: per-conversation sample snippets -->
      </div>
    </div>""")

        return f"""
<section class="section">
  <h2>🔀 Champion vs Challenger</h2>
  {"".join(cards)}
</section>"""

    def _render_leaderboard(
        self,
        slice_analysis: list[SliceResult],
    ) -> str:
        """Persona-based leaderboard — product differentiator (Review #13)."""
        if not slice_analysis:
            return ""

        # Group by slice dimension
        by_persona = [s for s in slice_analysis if s.slice_dimension == "persona_type"]
        by_scenario = [s for s in slice_analysis if s.slice_dimension == "scenario"]

        sections = []

        if by_persona:
            rows = self._render_slice_rows(by_persona)
            sections.append(f"""
      <div class="lb-section" id="lb-persona">
        <h3>Best Model per Persona Type</h3>
        <table class="slice-table sortable">
          <thead><tr><th>Persona Type</th><th>Winner</th><th>Runner-Up</th><th>Delta</th><th>Confidence</th></tr></thead>
          <tbody>{rows}</tbody>
        </table>
      </div>""")

        if by_scenario:
            rows = self._render_slice_rows(by_scenario)
            sections.append(f"""
      <div class="lb-section" id="lb-scenario">
        <h3>Best Model per Scenario</h3>
        <table class="slice-table sortable">
          <thead><tr><th>Scenario</th><th>Winner</th><th>Runner-Up</th><th>Delta</th><th>Confidence</th></tr></thead>
          <tbody>{rows}</tbody>
        </table>
      </div>""")

        if not sections:
            return ""

        # Tab buttons
        tabs = []
        if by_persona:
            tabs.append('<button class="tab-btn active" onclick="showTab(\'lb-persona\', this)">By Persona Type</button>')
        if by_scenario:
            tabs.append('<button class="tab-btn" onclick="showTab(\'lb-scenario\', this)">By Scenario</button>')

        return f"""
<section class="section">
  <h2>🏅 Leaderboard</h2>
  <div class="tab-bar">
    {"".join(tabs)}
  </div>
  {"".join(sections)}
</section>"""

    def _render_slice_rows(self, slices: list[SliceResult]) -> str:
        """Render slice analysis rows with enhanced data (Review #9)."""
        rows = []
        for s in slices:
            scores = s.model_scores
            if not scores:
                continue

            sorted_models = sorted(scores.items(), key=lambda x: -x[1])
            winner = sorted_models[0] if sorted_models else (None, 0)
            runner_up = sorted_models[1] if len(sorted_models) > 1 else (None, 0)

            delta = winner[1] - runner_up[1] if runner_up[0] else 0
            delta_cls = "delta-pos" if delta > 0.03 else "delta-zero"

            # Confidence based on score spread
            conf = "High" if delta > 0.1 else "Medium" if delta > 0.03 else "Low"
            conf_cls = f"conf-{conf.lower()}"

            winner_text = _esc(winner[0] or "—")
            runner_text = _esc(runner_up[0] or "—")
            label = s.slice_value.replace("_", " ").title()

            rows.append(
                f'<tr>'
                f'<td>{_esc(label)}</td>'
                f'<td class="pass">{winner_text} ({winner[1]:.2f})</td>'
                f'<td>{runner_text} ({runner_up[1]:.2f})</td>'
                f'<td class="{delta_cls}">{delta:+.3f}</td>'
                f'<td><span class="conf-badge {conf_cls}">{conf}</span></td>'
                f'</tr>'
            )
        return "".join(rows)

    def _render_cost_table(
        self,
        cost_analysis: list[CostEfficiency],
        cost_governance: list[CostGovernance],
    ) -> str:
        """Cost efficiency table (Review #3)."""
        if not cost_analysis:
            return ""

        gov_map = {g.model_id: g for g in cost_governance}

        rows = []
        for ce in sorted(cost_analysis, key=lambda x: x.cost_rank):
            gov = gov_map.get(ce.model_id)
            budget_alert = ""
            if gov and gov.budget_exceeded:
                budget_alert = ' <span class="budget-alert">OVER BUDGET</span>'

            rows.append(
                f'<tr>'
                f'<td>{_esc(ce.model_id)}{budget_alert}</td>'
                f'<td class="num">${ce.total_cost:.4f}</td>'
                f'<td class="num">{_fmt_cost(ce.cost_per_conversation)}</td>'
                f'<td class="num">{_fmt_cost(ce.cost_per_successful_conversation)}</td>'
                f'<td class="num">{_fmt_cost(ce.cost_per_grounded_answer)}</td>'
                f'<td class="num">{_fmt_qpd(ce.quality_per_dollar)}</td>'
                f'<td class="num">#{ce.cost_rank}</td>'
                f'</tr>'
            )

        return f"""
<section class="section">
  <h2>💰 Cost Efficiency</h2>
  <div class="table-wrapper">
    <table class="cost-table sortable" id="costTable">
      <thead>
        <tr>
          <th>Model</th>
          <th>Total Cost</th>
          <th>Cost/Conv</th>
          <th>Cost/Success</th>
          <th>Cost/Grounded</th>
          <th>Quality/$</th>
          <th>Rank</th>
        </tr>
      </thead>
      <tbody>{"".join(rows)}</tbody>
    </table>
  </div>
</section>"""

    def _render_forensics(self, forensics: list[FailureForensic]) -> str:
        """Failure forensics section."""
        if not forensics:
            return """
<section class="section">
  <h2>🔍 Failure Forensics</h2>
  <p class="no-data">No failures detected across models.</p>
</section>"""

        cards = []
        for f in forensics:
            root_causes_html = ""
            for rc in f.root_causes:
                sev_cls = rc.severity
                bucket_label = rc.bucket.value.replace("_", " ").title()
                root_causes_html += (
                    f'<div class="forensic-cause">'
                    f'<span class="severity-badge {sev_cls}">{_esc(rc.severity)}</span> '
                    f'<span class="root-bucket">{_esc(bucket_label)}</span> '
                    f'<span class="root-judge">({_esc(rc.judge_name)})</span>'
                    f'<div class="root-evidence">{_esc(rc.evidence)}</div>'
                    f'</div>'
                )

            regression_flag = ""
            if f.regression_vs_champion:
                regression_flag = '<span class="regression-flag">⚠️ Regression vs Champion</span>'

            cards.append(f"""
    <div class="forensic-card">
      <div class="forensic-header" onclick="this.parentElement.classList.toggle('expanded')">
        <span class="forensic-model">{_esc(f.model_id)}</span>
        {regression_flag}
        <span class="forensic-key">{_esc(f.conversation_key[:40])}</span>
        <span class="diff-expand">▶</span>
      </div>
      <div class="diff-body">
        {root_causes_html}
      </div>
    </div>""")

        return f"""
<section class="section">
  <h2>🔍 Failure Forensics</h2>
  <div class="filter-bar">
    <button class="filter-btn active" onclick="filterForensics('all', this)">All</button>
    <button class="filter-btn" onclick="filterForensics('regression', this)">Regressions Only</button>
    <button class="filter-btn" onclick="filterForensics('critical', this)">Critical Only</button>
  </div>
  {"".join(cards)}
</section>"""

    def _render_parity(
        self,
        parity_reports: list[CoverageParityReport],
        parity_status: str,
    ) -> str:
        """Coverage parity visualization (Review #2)."""
        if not parity_reports:
            return ""

        status_cls = _parity_css_class(parity_status)

        rows = []
        for p in parity_reports:
            rate_pct = p.completion_rate * 100
            bar_cls = "pass" if rate_pct >= 85 else "warn" if rate_pct >= 50 else "fail"
            warning = f'<div class="parity-warning">{_esc(p.parity_warning)}</div>' if p.parity_warning else ""

            rows.append(
                f'<tr>'
                f'<td>{_esc(p.model_id)}</td>'
                f'<td class="num">{p.total_cases}</td>'
                f'<td class="num">{p.completed_cases}</td>'
                f'<td>'
                f'  <div class="progress-bar"><div class="progress-fill {bar_cls}" style="width:{rate_pct:.0f}%"></div></div>'
                f'  <span class="progress-text">{rate_pct:.0f}%</span>'
                f'</td>'
                f'<td>{warning}</td>'
                f'</tr>'
            )

        return f"""
<section class="section">
  <h2>📏 Coverage Parity</h2>
  <div class="parity-status-banner {status_cls}">
    Overall Parity: <strong>{parity_status}</strong>
  </div>
  <div class="table-wrapper">
    <table class="parity-table">
      <thead><tr><th>Model</th><th>Total Cases</th><th>Completed</th><th>Completion Rate</th><th>Warning</th></tr></thead>
      <tbody>{"".join(rows)}</tbody>
    </table>
  </div>
</section>"""

    def _render_deployment_panel(
        self,
        rankings: list[ModelRanking],
        cost_analysis: list[CostEfficiency],
    ) -> str:
        """Deployment recommendation panel (Review #15)."""
        if not rankings:
            return ""

        cost_map = {c.model_id: c for c in cost_analysis}
        recs = []

        # Best overall
        top = rankings[0] if rankings else None
        if top and top.deployment_ready:
            recs.append(
                f'<div class="deploy-card deploy-prod">'
                f'<div class="deploy-icon">✅</div>'
                f'<div class="deploy-label">Recommended for Production</div>'
                f'<div class="deploy-model">{_esc(top.model_name)}</div>'
                f'<div class="deploy-reason">Rank #{top.overall_rank} · Score {top.overall_score:.3f}</div>'
                f'</div>'
            )
        elif top:
            blockers = "; ".join(top.deployment_blockers)
            recs.append(
                f'<div class="deploy-card deploy-no">'
                f'<div class="deploy-icon">❌</div>'
                f'<div class="deploy-label">Top Model Not Deployment-Ready</div>'
                f'<div class="deploy-model">{_esc(top.model_name)}</div>'
                f'<div class="deploy-reason">{_esc(blockers)}</div>'
                f'</div>'
            )

        # Cheapest usable
        cheapest = None
        for ce in sorted(cost_analysis, key=lambda x: x.cost_per_conversation or 999):
            r = next((r for r in rankings if r.model_id == ce.model_id), None)
            if r and r.deployment_ready:
                cheapest = (ce, r)
                break

        if cheapest and cheapest[1].model_id != (top.model_id if top else None):
            ce, r = cheapest
            recs.append(
                f'<div class="deploy-card deploy-cost">'
                f'<div class="deploy-icon">💰</div>'
                f'<div class="deploy-label">Recommended for Cost-Sensitive Use</div>'
                f'<div class="deploy-model">{_esc(r.model_name)}</div>'
                f'<div class="deploy-reason">{_fmt_cost(ce.cost_per_conversation)}/conv · Score {r.overall_score:.3f}</div>'
                f'</div>'
            )

        # Not recommended
        for r in rankings:
            if not r.deployment_ready:
                blockers = "; ".join(r.deployment_blockers[:2])
                recs.append(
                    f'<div class="deploy-card deploy-no">'
                    f'<div class="deploy-icon">❌</div>'
                    f'<div class="deploy-label">Not Recommended</div>'
                    f'<div class="deploy-model">{_esc(r.model_name)}</div>'
                    f'<div class="deploy-reason">{_esc(blockers)}</div>'
                    f'</div>'
                )

        if not recs:
            return ""

        return f"""
<section class="section">
  <h2>🚀 Deployment Recommendations</h2>
  <div class="deploy-grid">
    {"".join(recs)}
  </div>
</section>"""

    def _render_recommendations(self, recommendations: list[str]) -> str:
        """Recommendations section."""
        if not recommendations:
            return """
<section class="section">
  <h2>💡 Recommendations</h2>
  <p class="no-data">No recommendations — all metrics look healthy!</p>
</section>"""

        items = []
        for r in recommendations:
            if "❌" in r or "blocked" in r.lower():
                cls = "rec-critical"
            elif "⚠" in r or "DEGRADED" in r:
                cls = "rec-medium"
            else:
                cls = "rec-low"
            items.append(f'<div class="rec-item {cls}">{_esc(r)}</div>')

        return f"""
<section class="section">
  <h2>💡 Recommendations</h2>
  {"".join(items)}
</section>"""

    def _render_gates(self, gate_result: GateResult) -> str:
        """Gate checks table."""
        verdict_cls = "pass" if gate_result.passed else "fail"
        verdict_text = "PASS" if gate_result.passed else "FAIL"

        rows = []
        for gc in gate_result.checks:
            icon = "✅" if gc.passed else "❌"
            threshold_text = f"{gc.threshold:.2f}" if gc.threshold is not None else "—"
            actual_text = f"{gc.actual_value:.2f}" if gc.actual_value is not None else "—"

            rows.append(
                f'<tr>'
                f'<td>{icon}</td>'
                f'<td>{_esc(gc.name)}</td>'
                f'<td>{_esc(gc.reason)}</td>'
                f'<td class="num">{threshold_text}</td>'
                f'<td class="num">{actual_text}</td>'
                f'</tr>'
            )

        return f"""
<section class="section">
  <h2>🚦 CI/CD Gate Result</h2>
  <div class="gate-verdict {verdict_cls}">
    Gate Verdict: <strong>{verdict_text}</strong>
  </div>
  <div class="table-wrapper">
    <table class="gate-table">
      <thead><tr><th></th><th>Check</th><th>Reason</th><th>Threshold</th><th>Actual</th></tr></thead>
      <tbody>{"".join(rows)}</tbody>
    </table>
  </div>
  <div class="export-bar">
    <button class="export-btn" onclick="copyJSON()">📋 Copy JSON</button>
    <button class="export-btn" onclick="exportCSV()">📥 Export CSV</button>
  </div>
</section>"""


# ─────────────────────────────────────────────────────────────
# Helper Functions
# ─────────────────────────────────────────────────────────────

def _esc(text: str) -> str:
    """HTML-escape text."""
    return html.escape(str(text))


def _score_class(score: float) -> str:
    if score >= 0.8:
        return "pass"
    elif score >= 0.5:
        return "warn"
    return "fail"


def _score_color(score: float) -> str:
    if score >= 0.8:
        return "#6ee7b7"
    elif score >= 0.5:
        return "#fbbf24"
    return "#f87171"


def _detect_mode(report: MultiCompareReport) -> str:
    """Detect analysis mode from report context."""
    for rec in report.recommendations:
        if "STRICT" in rec.upper():
            return "STRICT"
    # Check gate checks for strict mode indicators
    for gc in report.gate_result.checks:
        if "strict" in gc.reason.lower():
            return "STRICT"
    return "EXPLORATORY"


def _compute_parity_status(parity_reports: list[CoverageParityReport]) -> str:
    """Compute overall parity status from reports."""
    if not parity_reports:
        return "OK"
    for p in parity_reports:
        if p.parity_warning and "invalid" in p.parity_warning.lower():
            return "INVALID"
    for p in parity_reports:
        if p.parity_warning and ("below" in p.parity_warning.lower() or "degraded" in p.parity_warning.lower()):
            return "DEGRADED"
    return "OK"


def _parity_css_class(status: str) -> str:
    return {"OK": "parity-ok", "DEGRADED": "parity-degraded", "INVALID": "parity-invalid"}.get(status, "")


def _has_low_confidence(rankings: list[ModelRanking]) -> bool:
    """Check if any dimension has low confidence."""
    for r in rankings:
        for ds in r.dimensions:
            if ds.statistical_verdict and ds.statistical_verdict.verdict.value == "insufficient_data":
                return True
            if ds.statistical_verdict and ds.statistical_verdict.sample_size < 5:
                return True
    return False


def _has_low_confidence_model(r: ModelRanking) -> bool:
    """Check if a specific model has low confidence on any dimension."""
    for ds in r.dimensions:
        if ds.statistical_verdict and ds.statistical_verdict.sample_size < 5:
            return True
    return False


def _is_tied_rank(r: ModelRanking, rankings: list[ModelRanking]) -> bool:
    """Check if this model's rank is tied with another."""
    return sum(1 for other in rankings if other.overall_rank == r.overall_rank) > 1


def _dimension_confidence(ds: DimensionScore) -> str:
    """Determine confidence level for a dimension score."""
    if ds.statistical_verdict:
        sv = ds.statistical_verdict
        if sv.sample_size >= 10:
            return "High"
        elif sv.sample_size >= 5:
            return "Medium"
        else:
            return "Low"
    return "Low"


def _collect_dimensions(rankings: list[ModelRanking]) -> list[Dimension]:
    """Collect all dimensions present across rankings."""
    dims: set[Dimension] = set()
    for r in rankings:
        for ds in r.dimensions:
            dims.add(ds.dimension)
    return sorted(dims, key=lambda d: d.value)


def _compute_normalization_ranges(
    rankings: list[ModelRanking],
    dims: list[Dimension],
) -> dict[Dimension, tuple[float, float]]:
    """Compute min/max per dimension for normalization (Review #4)."""
    ranges: dict[Dimension, tuple[float, float]] = {}
    for dim in dims:
        values = []
        for r in rankings:
            for ds in r.dimensions:
                if ds.dimension == dim:
                    values.append(ds.score)
        if values:
            ranges[dim] = (min(values), max(values))
        else:
            ranges[dim] = (0.0, 1.0)
    return ranges


def _normalize_score(
    raw: float,
    dim: Dimension,
    ranges: dict[Dimension, tuple[float, float]],
    is_inverted: bool,
) -> float:
    """Normalize a raw score to 0.0-1.0 for color mapping (Review #4)."""
    lo, hi = ranges.get(dim, (0.0, 1.0))

    # Score-type dimensions (0-1 range naturally)
    if dim not in INVERTED_DIMENSIONS and hi <= 1.0:
        norm = raw  # Already 0-1
    elif hi > lo:
        norm = (raw - lo) / (hi - lo)
    else:
        norm = 0.5

    # Invert for inverted dimensions (lower raw = better = higher norm)
    if is_inverted:
        norm = 1.0 - norm

    return max(0.0, min(1.0, norm))


def _heatmap_color(norm: float) -> str:
    """Map normalized 0-1 score to heatmap background color."""
    if norm >= 0.8:
        return "rgba(110,231,183,0.25)"
    elif norm >= 0.6:
        return "rgba(110,231,183,0.12)"
    elif norm >= 0.4:
        return "rgba(251,191,36,0.12)"
    elif norm >= 0.2:
        return "rgba(248,113,113,0.12)"
    else:
        return "rgba(248,113,113,0.25)"


def _format_raw_value(raw: float, dim: Dimension) -> str:
    """Format raw value for display based on dimension type."""
    if dim == Dimension.RESPONSE_LATENCY:
        return f"{raw:.0f}ms"
    elif dim == Dimension.COST_EFFICIENCY:
        return f"${raw:.4f}"
    elif dim == Dimension.CRITICAL_FAILURE_RATE:
        return f"{raw:.0%}"
    else:
        return f"{raw:.3f}"


def _evidence_tooltip(ds: DimensionScore) -> str:
    """Build tooltip with evidence transparency (Review #8)."""
    parts = [f"Dimension: {ds.dimension.value}"]
    parts.append(f"Score: {ds.score:.4f}")
    parts.append(f"Rank: {ds.rank}")

    if ds.statistical_verdict:
        sv = ds.statistical_verdict
        parts.append(f"Sample size: {sv.sample_size}")
        parts.append(f"Method: {sv.method}")
        parts.append(f"Significance: {sv.practical_significance}")
        parts.append("Evidence: summary-level")

    if ds.delta_from_champion is not None:
        parts.append(f"Delta vs champion: {ds.delta_from_champion:+.4f}")

    return " | ".join(parts)


def _render_diff_list(items: list[str], icon: str, cls: str) -> str:
    """Render a diff win/loss/neutral list."""
    if not items:
        return f'<div class="diff-empty">No {cls}s</div>'
    li_items = "".join(f'<li class="evidence-item ev-{cls}">{_esc(item)}</li>' for item in items)
    return f'<div class="diff-list"><strong>{icon} {cls.title()}s ({len(items)})</strong><ul>{li_items}</ul></div>'


def _fmt_cost(value: float | None) -> str:
    """Format a cost value."""
    if value is None:
        return "—"
    return f"${value:.4f}"


def _fmt_qpd(value: float | None) -> str:
    """Format quality-per-dollar."""
    if value is None:
        return "—"
    return f"{value:.1f}"


def _get_profile_weights(profile_name: str) -> dict[str, float] | None:
    """Get weight distribution for a profile."""
    from src.multi_compare.models import BUILT_IN_PROFILES
    profile = BUILT_IN_PROFILES.get(profile_name)
    if profile:
        return profile.weights
    return None


def _profile_description(name: str) -> str:
    """Get profile description."""
    descriptions = {
        "balanced": "All dimensions equally weighted — general-purpose evaluation.",
        "safety_first": "Healthcare, finance, regulated industries — safety and compliance prioritized.",
        "quality_first": "Customer-facing chatbots, content generation — quality and relevance prioritized.",
        "cost_optimized": "High-volume, cost-sensitive deployments — cost efficiency prioritized.",
        "compliance_first": "Enterprise compliance, audit-heavy environments — policy compliance prioritized.",
        "low_latency": "Real-time applications, user-facing APIs — response speed prioritized.",
    }
    return descriptions.get(name, "Custom decision profile.")


def _profile_influence_note(name: str, matrix: ComparisonMatrix) -> str:
    """Generate a plain-English influence note."""
    if not matrix.rankings:
        return ""
    top = matrix.rankings[0]
    if not top.dimensions:
        return ""

    # Find the highest-weighted dimension where the winner excels
    weights = _get_profile_weights(name)
    if not weights:
        return ""

    best_dim = None
    best_impact = 0.0
    for ds in top.dimensions:
        w = weights.get(ds.dimension.value, 0)
        impact = ds.score * w
        if impact > best_impact:
            best_impact = impact
            best_dim = ds.dimension

    if best_dim:
        dim_label = best_dim.value.replace("_", " ").title()
        profile_label = name.replace("_", " ").title()
        return (
            f"{profile_label} profile favored {top.model_name} "
            f"due to strong {dim_label} performance."
        )
    return ""


def _safe_json_serialize(report: MultiCompareReport) -> str:
    """Safely serialize report to JSON for export."""
    try:
        data = report.model_dump(mode="json")
        return json.dumps(data, indent=2, default=str)
    except Exception:
        return "{}"


# ─────────────────────────────────────────────────────────────
# CSS
# ─────────────────────────────────────────────────────────────

def _get_css() -> str:
    return """
:root {
  --bg: #0c0e14; --surface: #151822; --surface2: #1c2030; --border: #2a2f42;
  --text: #e2e4ec; --dim: #8890a8; --pass: #6ee7b7; --warn: #fbbf24; --fail: #f87171;
  --accent: #38bdf8; --champion: #f59e0b; --winner: #34d399;
  --rank1: #fbbf24; --rank2: #94a3b8; --rank3: #cd7f32;
}
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: var(--bg); color: var(--text); line-height: 1.6; padding-top: 48px; }

/* Sticky Header (Review #12) */
.sticky-header { position: fixed; top: 0; left: 0; right: 0; z-index: 100; background: var(--surface); border-bottom: 1px solid var(--border); padding: 0.5rem 2rem; display: flex; align-items: center; gap: 0.75rem; font-size: 0.85rem; backdrop-filter: blur(8px); }
.sh-label { color: var(--dim); }
.sh-value { font-weight: 700; }
.sh-value.pass { color: var(--pass); }
.sh-value.dim { color: var(--dim); font-style: italic; }
.sh-divider { color: var(--border); }
.sh-badge { padding: 0.1rem 0.5rem; border-radius: 4px; font-weight: 700; font-size: 0.75rem; text-transform: uppercase; }
.sh-badge.pass { background: rgba(110,231,183,0.15); color: var(--pass); }
.sh-badge.fail { background: rgba(248,113,113,0.15); color: var(--fail); }
.sh-badge.parity-ok { background: rgba(110,231,183,0.15); color: var(--pass); }
.sh-badge.parity-degraded { background: rgba(251,191,36,0.15); color: var(--warn); }
.sh-badge.parity-invalid { background: rgba(248,113,113,0.15); color: var(--fail); }
.sh-alert { color: var(--warn); font-weight: 600; }

/* Header */
header { padding: 2rem 2rem 1rem; border-bottom: 1px solid var(--border); }
.header-top { display: flex; align-items: center; gap: 0.75rem; }
h1 { font-size: 1.75rem; font-weight: 700; }
.header-badge { background: var(--surface2); border: 1px solid var(--border); padding: 0.15rem 0.5rem; border-radius: 4px; font-size: 0.75rem; color: var(--dim); }
.header-meta { margin-top: 0.25rem; display: flex; gap: 1rem; align-items: center; }
.header-sub { color: var(--dim); font-size: 0.9rem; }
.header-dim { color: var(--dim); font-size: 0.75rem; font-family: monospace; }
.header-badges { display: flex; gap: 0.5rem; margin-top: 0.75rem; flex-wrap: wrap; }
.mode-badge { padding: 0.2rem 0.65rem; border-radius: 4px; font-size: 0.75rem; font-weight: 700; text-transform: uppercase; }
.badge-strict { background: rgba(248,113,113,0.15); color: var(--fail); border: 1px solid rgba(248,113,113,0.3); }
.badge-exploratory { background: rgba(56,189,248,0.15); color: var(--accent); border: 1px solid rgba(56,189,248,0.3); }
.comp-badge { background: var(--surface2); border: 1px solid var(--border); padding: 0.2rem 0.65rem; border-radius: 4px; font-size: 0.75rem; color: var(--dim); }
.profile-badge { background: rgba(251,191,36,0.1); border: 1px solid rgba(251,191,36,0.2); padding: 0.2rem 0.65rem; border-radius: 4px; font-size: 0.75rem; color: var(--warn); }
.model-count { color: var(--dim); font-size: 0.85rem; }
h2 { font-size: 1.3rem; font-weight: 700; margin-bottom: 1rem; }
h3 { font-size: 1rem; font-weight: 600; margin-bottom: 0.75rem; color: var(--dim); }

/* Global Warnings (Review #1, #2) */
.warning-banner { padding: 0 2rem; }
.global-warning { padding: 0.75rem 1rem; margin: 0.5rem 0; border-radius: 8px; font-size: 0.88rem; border-left: 4px solid var(--warn); background: rgba(251,191,36,0.06); }

/* Sections */
.section { padding: 1.5rem 2rem; border-top: 1px solid var(--border); }
.section-hint { color: var(--dim); font-size: 0.85rem; margin-bottom: 1rem; }
.no-data { color: var(--dim); font-style: italic; }

/* Scorecards (Review #2, #3) */
.scorecard-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(220px, 1fr)); gap: 0.75rem; }
.scorecard { background: var(--surface); border: 1px solid var(--border); border-radius: 10px; padding: 1.25rem; text-align: center; position: relative; transition: border-color 0.2s; }
.scorecard:hover { border-color: var(--accent); }
.champion-card { border-color: var(--champion); border-width: 2px; }
.winner-card { border-color: var(--winner); border-width: 2px; }
.sc-rank { font-size: 1.5rem; font-weight: 800; margin-bottom: 0.25rem; }
.sc-name { font-weight: 600; font-size: 0.95rem; margin-bottom: 0.1rem; }
.sc-id { font-size: 0.75rem; color: var(--dim); font-family: monospace; margin-bottom: 0.5rem; }
.sc-score { font-size: 2rem; font-weight: 800; font-variant-numeric: tabular-nums; }
.sc-deploy { font-size: 1.2rem; margin-top: 0.5rem; }
.sc-champion-tag { position: absolute; top: -1px; right: -1px; background: var(--champion); color: #000; padding: 0.1rem 0.5rem; border-radius: 0 8px 0 8px; font-size: 0.65rem; font-weight: 700; text-transform: uppercase; }
.sc-winner-tag { position: absolute; top: -1px; left: -1px; background: var(--winner); color: #000; padding: 0.1rem 0.5rem; border-radius: 8px 0 8px 0; font-size: 0.65rem; font-weight: 700; text-transform: uppercase; }
.rank-tied { font-size: 0.65rem; color: var(--warn); display: block; }
.rank-unconfirmed { font-size: 0.6rem; color: var(--dim); display: block; font-style: italic; }
.parity-badge { font-size: 0.7rem; vertical-align: super; }
.parity-degraded { color: var(--warn); }
.parity-invalid { color: var(--fail); }

.no-winner-banner { background: rgba(251,191,36,0.08); border: 1px solid rgba(251,191,36,0.2); border-radius: 10px; padding: 1rem; text-align: center; margin-bottom: 1rem; display: flex; align-items: center; justify-content: center; gap: 0.75rem; }
.nw-icon { font-size: 1.5rem; }
.nw-text { color: var(--warn); font-weight: 600; }

/* Profile Panel (Review #10) */
.profile-panel { }
.profile-desc { color: var(--dim); font-size: 0.88rem; margin-bottom: 1rem; }
.profile-weights { max-width: 600px; }
.pw-row { display: flex; align-items: center; gap: 0.75rem; margin-bottom: 0.35rem; }
.pw-label { font-size: 0.8rem; color: var(--dim); width: 140px; text-align: right; flex-shrink: 0; }
.pw-bar-bg { flex: 1; height: 14px; background: var(--surface2); border-radius: 7px; overflow: hidden; }
.pw-bar { height: 100%; background: var(--accent); border-radius: 7px; transition: width 0.3s; }
.pw-pct { font-size: 0.75rem; color: var(--dim); width: 36px; }
.profile-influence { margin-top: 0.75rem; color: var(--dim); font-size: 0.85rem; font-style: italic; padding: 0.5rem 0.75rem; border-left: 3px solid var(--accent); background: rgba(56,189,248,0.05); border-radius: 0 6px 6px 0; }

/* Heatmap (Review #4) */
.table-wrapper { overflow-x: auto; }
.heatmap-table { width: 100%; border-collapse: collapse; font-size: 0.85rem; }
.heatmap-table th { text-align: center; font-size: 0.72rem; color: var(--dim); text-transform: uppercase; padding: 0.5rem; border-bottom: 1px solid var(--border); cursor: pointer; user-select: none; white-space: nowrap; }
.hm-model-header { text-align: left !important; }
.hm-dim-header { min-width: 90px; }
.hm-model { font-weight: 600; padding: 0.5rem; white-space: nowrap; }
.hm-champion-row { border-left: 3px solid var(--champion); }
.hm-cell { padding: 0.5rem; text-align: center; border-bottom: 1px solid rgba(42,47,66,0.3); position: relative; }
.hm-na { color: var(--dim); }
.hm-raw { font-weight: 600; font-variant-numeric: tabular-nums; }
.hm-star { color: var(--champion); font-size: 0.8rem; }
.hm-delta { font-size: 0.7rem; margin-top: 2px; }
.delta-pos { color: var(--pass); }
.delta-neg { color: var(--fail); }
.delta-zero { color: var(--dim); }
.hm-meta { display: flex; justify-content: center; align-items: center; gap: 4px; margin-top: 2px; }
.hm-verdict { font-size: 0.6rem; color: var(--dim); }
.inv-mark { color: var(--accent); font-weight: 700; }

/* Confidence badges (Review #1) */
.conf-badge { display: inline-block; width: 16px; height: 16px; line-height: 16px; border-radius: 50%; text-align: center; font-size: 0.6rem; font-weight: 700; }
.conf-high { background: rgba(110,231,183,0.2); color: var(--pass); }
.conf-medium { background: rgba(251,191,36,0.2); color: var(--warn); }
.conf-low { background: rgba(248,113,113,0.2); color: var(--fail); }

/* Charts */
.charts-row { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 1rem; }
.chart-card { background: var(--surface); border: 1px solid var(--border); border-radius: 10px; padding: 1.25rem; }

/* Diff Cards (Review #5, #16) */
.diff-card { background: var(--surface); border: 1px solid var(--border); border-radius: 10px; margin-bottom: 0.5rem; overflow: hidden; }
.diff-header { display: flex; align-items: center; gap: 0.75rem; padding: 0.75rem 1rem; cursor: pointer; user-select: none; transition: background 0.15s; flex-wrap: wrap; }
.diff-header:hover { background: var(--surface2); }
.diff-title { font-weight: 600; font-size: 0.9rem; }
.diff-summary { color: var(--dim); font-size: 0.82rem; flex: 1; }
.diff-evidence-count { font-size: 0.75rem; color: var(--accent); background: rgba(56,189,248,0.1); padding: 0.1rem 0.5rem; border-radius: 10px; }
.diff-expand { color: var(--dim); font-size: 0.8rem; transition: transform 0.2s; }
.diff-card.expanded .diff-expand { transform: rotate(90deg); }
.diff-body { display: none; padding: 0.75rem 1rem; border-top: 1px solid var(--border); }
.diff-card.expanded .diff-body { display: block; }
.diff-lists { display: grid; grid-template-columns: repeat(3, 1fr); gap: 1rem; margin-top: 0.75rem; }
.diff-list ul { padding-left: 1.2rem; margin-top: 0.35rem; }
.diff-empty { color: var(--dim); font-size: 0.82rem; font-style: italic; }
.evidence-item { font-size: 0.82rem; margin-bottom: 0.25rem; }
.ev-win { color: var(--pass); }
.ev-loss { color: var(--fail); }
.ev-neutral { color: var(--dim); }
.top-evidence { margin-bottom: 0.5rem; font-size: 0.85rem; }
.top-evidence strong { color: var(--dim); }
.top-evidence ul { padding-left: 1.2rem; margin-top: 0.25rem; }
.uncertainty-note { margin-top: 0.75rem; padding: 0.5rem 0.75rem; border-radius: 6px; background: rgba(251,191,36,0.08); border: 1px solid rgba(251,191,36,0.15); color: var(--warn); font-size: 0.82rem; }

/* Leaderboard (Review #13) */
.tab-bar { display: flex; gap: 0.5rem; margin-bottom: 1rem; }
.tab-btn { background: var(--surface2); border: 1px solid var(--border); border-radius: 6px; padding: 0.35rem 1rem; font-size: 0.82rem; color: var(--dim); cursor: pointer; transition: all 0.15s; }
.tab-btn:hover { border-color: var(--accent); color: var(--text); }
.tab-btn.active { background: rgba(56,189,248,0.15); border-color: var(--accent); color: var(--accent); }
.lb-section { }
.lb-section:not(:first-of-type) { display: none; }
.slice-table { width: 100%; border-collapse: collapse; }
.slice-table th { text-align: left; font-size: 0.75rem; color: var(--dim); text-transform: uppercase; padding: 0.5rem 0.75rem; border-bottom: 1px solid var(--border); cursor: pointer; }
.slice-table td { padding: 0.5rem 0.75rem; border-bottom: 1px solid rgba(42,47,66,0.3); font-size: 0.85rem; }

/* Cost Table */
.cost-table { width: 100%; border-collapse: collapse; }
.cost-table th { text-align: left; font-size: 0.75rem; color: var(--dim); text-transform: uppercase; padding: 0.5rem 0.75rem; border-bottom: 1px solid var(--border); cursor: pointer; }
.cost-table td { padding: 0.5rem 0.75rem; border-bottom: 1px solid rgba(42,47,66,0.3); font-size: 0.85rem; }
.num { text-align: right; font-variant-numeric: tabular-nums; font-family: monospace; }
.budget-alert { background: rgba(248,113,113,0.15); color: var(--fail); padding: 0.1rem 0.4rem; border-radius: 4px; font-size: 0.7rem; font-weight: 700; margin-left: 0.5rem; }

/* Forensics */
.forensic-card { background: var(--surface); border: 1px solid var(--border); border-radius: 10px; margin-bottom: 0.5rem; overflow: hidden; }
.forensic-header { display: flex; align-items: center; gap: 0.75rem; padding: 0.75rem 1rem; cursor: pointer; transition: background 0.15s; }
.forensic-header:hover { background: var(--surface2); }
.forensic-model { font-weight: 600; }
.forensic-key { font-size: 0.75rem; color: var(--dim); font-family: monospace; margin-left: auto; }
.regression-flag { font-size: 0.75rem; color: var(--warn); font-weight: 600; }
.forensic-cause { padding: 0.5rem 0; border-bottom: 1px solid rgba(42,47,66,0.3); }
.forensic-cause:last-child { border-bottom: none; }
.root-bucket { font-weight: 600; }
.root-judge { color: var(--dim); font-size: 0.82rem; }
.root-evidence { color: var(--dim); font-size: 0.82rem; margin-top: 0.25rem; }
.severity-badge { font-size: 0.7rem; padding: 0.1rem 0.45rem; border-radius: 4px; text-transform: uppercase; font-weight: 600; }
.severity-badge.critical { background: rgba(248,113,113,0.15); color: var(--fail); }
.severity-badge.medium { background: rgba(251,191,36,0.15); color: var(--warn); }
.severity-badge.low { background: rgba(110,231,183,0.15); color: var(--pass); }

/* Filter bar (Review #7) */
.filter-bar { display: flex; gap: 0.5rem; margin-bottom: 1rem; }
.filter-btn { background: var(--surface2); border: 1px solid var(--border); border-radius: 6px; padding: 0.3rem 0.75rem; font-size: 0.78rem; color: var(--dim); cursor: pointer; }
.filter-btn:hover { border-color: var(--accent); }
.filter-btn.active { background: rgba(56,189,248,0.15); border-color: var(--accent); color: var(--accent); }

/* Parity (Review #2) */
.parity-status-banner { padding: 0.75rem 1rem; border-radius: 8px; text-align: center; margin-bottom: 1rem; font-size: 0.9rem; }
.parity-ok { background: rgba(110,231,183,0.08); border: 1px solid rgba(110,231,183,0.2); color: var(--pass); }
.parity-degraded { background: rgba(251,191,36,0.08); border: 1px solid rgba(251,191,36,0.2); color: var(--warn); }
.parity-invalid { background: rgba(248,113,113,0.08); border: 1px solid rgba(248,113,113,0.2); color: var(--fail); }
.parity-table { width: 100%; border-collapse: collapse; }
.parity-table th { text-align: left; font-size: 0.75rem; color: var(--dim); text-transform: uppercase; padding: 0.5rem 0.75rem; border-bottom: 1px solid var(--border); }
.parity-table td { padding: 0.5rem 0.75rem; border-bottom: 1px solid rgba(42,47,66,0.3); }
.parity-warning { color: var(--warn); font-size: 0.78rem; }
.progress-bar { display: inline-block; width: 120px; height: 10px; background: var(--surface2); border-radius: 5px; overflow: hidden; vertical-align: middle; margin-right: 0.5rem; }
.progress-fill { height: 100%; border-radius: 5px; }
.progress-fill.pass { background: var(--pass); }
.progress-fill.warn { background: var(--warn); }
.progress-fill.fail { background: var(--fail); }
.progress-text { font-size: 0.82rem; font-variant-numeric: tabular-nums; }

/* Deployment Panel (Review #15) */
.deploy-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(260px, 1fr)); gap: 0.75rem; }
.deploy-card { background: var(--surface); border: 1px solid var(--border); border-radius: 10px; padding: 1.25rem; text-align: center; }
.deploy-prod { border-color: var(--pass); }
.deploy-cost { border-color: var(--warn); }
.deploy-no { border-color: var(--fail); }
.deploy-icon { font-size: 2rem; margin-bottom: 0.5rem; }
.deploy-label { font-weight: 700; font-size: 0.9rem; margin-bottom: 0.35rem; }
.deploy-model { font-size: 1rem; color: var(--accent); font-weight: 600; }
.deploy-reason { font-size: 0.8rem; color: var(--dim); margin-top: 0.25rem; }

/* Recommendations */
.rec-item { padding: 0.6rem 1rem; border-radius: 8px; margin-bottom: 0.5rem; font-size: 0.9rem; border-left: 3px solid; }
.rec-critical { background: rgba(248,113,113,0.08); border-color: var(--fail); }
.rec-medium { background: rgba(251,191,36,0.08); border-color: var(--warn); }
.rec-low { background: rgba(110,231,183,0.08); border-color: var(--pass); }

/* Gate Table */
.gate-verdict { padding: 0.75rem 1rem; border-radius: 8px; text-align: center; margin-bottom: 1rem; font-size: 1rem; }
.gate-verdict.pass { background: rgba(110,231,183,0.08); border: 1px solid rgba(110,231,183,0.2); color: var(--pass); }
.gate-verdict.fail { background: rgba(248,113,113,0.08); border: 1px solid rgba(248,113,113,0.2); color: var(--fail); }
.gate-table { width: 100%; border-collapse: collapse; }
.gate-table th { text-align: left; font-size: 0.75rem; color: var(--dim); text-transform: uppercase; padding: 0.5rem 0.75rem; border-bottom: 1px solid var(--border); }
.gate-table td { padding: 0.5rem 0.75rem; border-bottom: 1px solid rgba(42,47,66,0.3); font-size: 0.85rem; }

/* Export bar (Review #11) */
.export-bar { display: flex; gap: 0.5rem; margin-top: 1rem; justify-content: flex-end; }
.export-btn { background: var(--surface2); border: 1px solid var(--border); border-radius: 6px; padding: 0.4rem 1rem; font-size: 0.82rem; color: var(--dim); cursor: pointer; transition: all 0.15s; }
.export-btn:hover { border-color: var(--accent); color: var(--text); }

/* Footer */
footer { text-align: center; padding: 2rem; color: var(--dim); font-size: 0.8rem; border-top: 1px solid var(--border); }

/* Pass/Warn/Fail */
.pass { color: var(--pass); }
.warn { color: var(--warn); }
.fail { color: var(--fail); }

/* Responsive */
@media (max-width: 768px) {
  .sticky-header { padding: 0.4rem 1rem; font-size: 0.75rem; }
  body { padding-top: 40px; }
  .scorecard-grid { grid-template-columns: 1fr 1fr; }
  .charts-row { grid-template-columns: 1fr; }
  .diff-lists { grid-template-columns: 1fr; }
  header, .section { padding-left: 1rem; padding-right: 1rem; }
}
"""


# ─────────────────────────────────────────────────────────────
# JavaScript
# ─────────────────────────────────────────────────────────────

def _get_dashboard_js(
    rankings: list[ModelRanking],
    cost_analysis: list[CostEfficiency],
    report_json: str,
) -> str:
    """Generate all dashboard JavaScript."""
    # Prepare chart data
    models = [r.model_name for r in sorted(rankings, key=lambda x: x.overall_rank)]
    model_ids = [r.model_id for r in sorted(rankings, key=lambda x: x.overall_rank)]

    # Collect dimensions for bar chart
    all_dims = _collect_dimensions(rankings)
    dim_labels = [d.value.replace("_", " ").title() for d in all_dims]

    # Build datasets for grouped bar chart
    colors = ["#38bdf8", "#6ee7b7", "#fbbf24", "#f87171", "#a78bfa",
              "#fb923c", "#94a3b8", "#f472b6", "#34d399", "#60a5fa"]
    bar_datasets = []
    for i, r in enumerate(sorted(rankings, key=lambda x: x.overall_rank)):
        dim_scores = {ds.dimension: ds.score for ds in r.dimensions}
        data = []
        for dim in all_dims:
            score = dim_scores.get(dim, 0)
            # For inverted dims, show 1-score for visual comparison
            if dim in INVERTED_DIMENSIONS:
                score = max(0, 1 - min(score, 1.0))
            data.append(round(score * 100, 1))
        bar_datasets.append({
            "label": r.model_name,
            "data": data,
            "backgroundColor": colors[i % len(colors)],
            "borderRadius": 4,
        })

    # Radar chart data
    # Use non-inverted dimension labels for radar
    radar_dims = [d for d in all_dims if d not in INVERTED_DIMENSIONS][:8]
    radar_labels = [d.value.replace("_", " ").title() for d in radar_dims]
    radar_datasets = []
    for i, r in enumerate(sorted(rankings, key=lambda x: x.overall_rank)):
        dim_scores = {ds.dimension: ds.score for ds in r.dimensions}
        data = [round(dim_scores.get(d, 0) * 100, 1) for d in radar_dims]
        color = colors[i % len(colors)]
        radar_datasets.append({
            "label": r.model_name,
            "data": data,
            "borderColor": color,
            "backgroundColor": color.replace(")", ",0.1)").replace("rgb", "rgba") if "rgb" in color else f"{color}1a",
            "pointRadius": 3,
            "fill": True,
        })

    # Cost vs Quality scatter data
    cost_map = {c.model_id: c for c in cost_analysis}
    scatter_data = []
    for r in sorted(rankings, key=lambda x: x.overall_rank):
        ce = cost_map.get(r.model_id)
        cost = ce.total_cost if ce else 0
        scatter_data.append({
            "x": round(cost, 4),
            "y": round(r.overall_score * 100, 1),
            "label": r.model_name,
        })

    scatter_datasets = []
    for i, pt in enumerate(scatter_data):
        scatter_datasets.append({
            "label": pt["label"],
            "data": [{"x": pt["x"], "y": pt["y"]}],
            "backgroundColor": colors[i % len(colors)],
            "pointRadius": 8,
            "pointHoverRadius": 12,
        })

    return f"""
// ---- Chart.js Initialization ----
const chartColors = {json.dumps(colors)};

// Dimension Bar Chart
new Chart(document.getElementById('dimensionBarChart'), {{
  type: 'bar',
  data: {{
    labels: {json.dumps(dim_labels)},
    datasets: {json.dumps(bar_datasets)}
  }},
  options: {{
    responsive: true,
    plugins: {{ legend: {{ position: 'bottom', labels: {{ color: '#8890a8', padding: 8, font: {{ size: 11 }} }} }} }},
    scales: {{
      y: {{ min: 0, max: 100, grid: {{ color: '#1c2030' }}, ticks: {{ color: '#8890a8' }} }},
      x: {{ grid: {{ display: false }}, ticks: {{ color: '#e2e4ec', font: {{ size: 10 }}, maxRotation: 45 }} }}
    }}
  }}
}});

// Radar Chart
new Chart(document.getElementById('radarChart'), {{
  type: 'radar',
  data: {{
    labels: {json.dumps(radar_labels)},
    datasets: {json.dumps(radar_datasets)}
  }},
  options: {{
    responsive: true,
    scales: {{
      r: {{
        min: 0, max: 100,
        grid: {{ color: '#1c2030' }},
        angleLines: {{ color: '#1c2030' }},
        pointLabels: {{ color: '#8890a8', font: {{ size: 10 }} }},
        ticks: {{ color: '#8890a8', backdropColor: 'transparent', stepSize: 25 }}
      }}
    }},
    plugins: {{ legend: {{ position: 'bottom', labels: {{ color: '#8890a8', padding: 8, font: {{ size: 11 }} }} }} }}
  }}
}});

// Cost vs Quality Scatter
new Chart(document.getElementById('costQualityChart'), {{
  type: 'scatter',
  data: {{
    datasets: {json.dumps(scatter_datasets)}
  }},
  options: {{
    responsive: true,
    plugins: {{
      legend: {{ position: 'bottom', labels: {{ color: '#8890a8', padding: 8, font: {{ size: 11 }} }} }},
      tooltip: {{
        callbacks: {{
          label: (ctx) => ctx.dataset.label + ': $' + ctx.raw.x.toFixed(4) + ' / ' + ctx.raw.y.toFixed(1) + '%'
        }}
      }}
    }},
    scales: {{
      x: {{ title: {{ display: true, text: 'Total Cost ($)', color: '#8890a8' }}, grid: {{ color: '#1c2030' }}, ticks: {{ color: '#8890a8' }} }},
      y: {{ title: {{ display: true, text: 'Overall Score (%)', color: '#8890a8' }}, min: 0, max: 100, grid: {{ color: '#1c2030' }}, ticks: {{ color: '#8890a8' }} }}
    }}
  }}
}});

// ---- Interactive Features ----

// Collapsible sections
document.querySelectorAll('.diff-header, .forensic-header').forEach(el => {{
  el.addEventListener('click', () => {{
    el.parentElement.classList.toggle('expanded');
  }});
}});

// Tab switching (Review #13)
function showTab(id, btn) {{
  const section = btn.closest('.section');
  section.querySelectorAll('.lb-section').forEach(s => s.style.display = 'none');
  section.querySelector('#' + id).style.display = 'block';
  section.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));
  btn.classList.add('active');
}}

// Table sorting (Review #7)
document.querySelectorAll('.sortable th').forEach(th => {{
  th.addEventListener('click', () => {{
    const table = th.closest('table');
    const tbody = table.querySelector('tbody');
    const rows = Array.from(tbody.querySelectorAll('tr'));
    const col = th.cellIndex;
    const dir = th.dataset.sortDir === 'asc' ? 'desc' : 'asc';
    th.dataset.sortDir = dir;

    rows.sort((a, b) => {{
      let va = a.cells[col]?.textContent.trim() || '';
      let vb = b.cells[col]?.textContent.trim() || '';
      // Try numeric comparison
      const na = parseFloat(va.replace(/[$%#,TH]/g, ''));
      const nb = parseFloat(vb.replace(/[$%#,TH]/g, ''));
      if (!isNaN(na) && !isNaN(nb)) {{
        return dir === 'asc' ? na - nb : nb - na;
      }}
      return dir === 'asc' ? va.localeCompare(vb) : vb.localeCompare(va);
    }});

    rows.forEach(row => tbody.appendChild(row));
  }});
}});

// Forensics filtering (Review #7)
function filterForensics(type, btn) {{
  const section = btn.closest('.section');
  section.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active'));
  btn.classList.add('active');
  section.querySelectorAll('.forensic-card').forEach(card => {{
    if (type === 'all') {{
      card.style.display = 'block';
    }} else if (type === 'regression') {{
      card.style.display = card.querySelector('.regression-flag') ? 'block' : 'none';
    }} else if (type === 'critical') {{
      card.style.display = card.querySelector('.severity-badge.critical') ? 'block' : 'none';
    }}
  }});
}}

// Export: Copy JSON (Review #11)
function copyJSON() {{
  const json = {json.dumps(report_json)};
  navigator.clipboard.writeText(json).then(() => {{
    const btn = document.querySelector('.export-btn');
    const orig = btn.textContent;
    btn.textContent = '✅ Copied!';
    setTimeout(() => btn.textContent = orig, 2000);
  }}).catch(() => alert('Copy failed — use Ctrl+C'));
}}

// Export: CSV (Review #11)
function exportCSV() {{
  const table = document.getElementById('heatmapTable');
  if (!table) return;
  const rows = Array.from(table.querySelectorAll('tr'));
  const csv = rows.map(row =>
    Array.from(row.querySelectorAll('th, td')).map(cell =>
      '"' + cell.textContent.trim().replace(/"/g, '""') + '"'
    ).join(',')
  ).join('\\n');
  const blob = new Blob([csv], {{ type: 'text/csv' }});
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = 'multi_compare_heatmap.csv'; a.click();
  URL.revokeObjectURL(url);
}}
"""
