"""initial schema

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-04-13

Postgres + Auth Wiring Sprint Turn 1 — the single initial migration that
creates all 12 tables from plan §7.0, applies RLS with FORCE to the 11
tenant-scoped tables (plan §5), creates the `memberships` partial unique
indexes (plan §7.1 — the v0.5.1 MF-1 fix), and partitions `audit_events`
with a DEFAULT partition for write safety (plan §7.2 — the v0.4 MF-5 fix).

Hand-written, not autogenerated, because:
  - Partitioned tables require raw CREATE TABLE ... PARTITION BY ...
  - FORCE ROW LEVEL SECURITY is not modeled by SQLAlchemy declarative
  - Partial unique indexes on nullable columns need explicit WHERE clauses
  - RLS policies with USING/WITH CHECK are not modeled by alembic autogen

Zero data rows are created by this migration. Dev tenant seeding lives in
`scripts/seed_dev_tenant.py` per plan §6.4.
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import INET, JSONB, UUID


# revision identifiers, used by Alembic.
revision: str = "0001_initial_schema"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ---------------------------------------------------------------------------
# RLS scope
# ---------------------------------------------------------------------------
# Every table below gets tenant-level RLS. `tenants` itself does NOT because
# it is the join target from memberships; access control happens through
# memberships, not RLS (plan §7.0 note).
# ---------------------------------------------------------------------------

RLS_TABLES = [
    "workspaces",
    "memberships",
    "service_accounts",
    "api_keys",
    "assets",
    "runs",
    "conversation_summaries",
    "dashboard_artifacts",
    "comparisons",
    "idempotency_keys",
    "audit_events",
]


def upgrade() -> None:
    # -----------------------------------------------------------------
    # Required Postgres extensions
    # -----------------------------------------------------------------
    # gen_random_uuid() lives in pgcrypto. Neon / modern PG ship with it
    # but not always pre-created.
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')

    # -----------------------------------------------------------------
    # 1. tenants — root table, no RLS
    # -----------------------------------------------------------------
    op.create_table(
        "tenants",
        sa.Column(
            "id",
            UUID(as_uuid=False),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("slug", sa.String(64), nullable=False),
        sa.Column("clerk_org_id", sa.String(255), nullable=True),
        sa.Column(
            "plan_id",
            sa.String(32),
            nullable=False,
            server_default=sa.text("'free'"),
        ),
        sa.Column(
            "settings",
            JSONB,
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.UniqueConstraint("slug", name="uq_tenants_slug"),
    )
    op.create_index(
        "uq_tenants_clerk_org_id",
        "tenants",
        ["clerk_org_id"],
        unique=True,
        postgresql_where=sa.text("clerk_org_id IS NOT NULL"),
    )

    # -----------------------------------------------------------------
    # 2. workspaces
    # -----------------------------------------------------------------
    op.create_table(
        "workspaces",
        sa.Column(
            "id",
            UUID(as_uuid=False),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("tenant_id", UUID(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column(
            "is_default",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            ondelete="CASCADE",
            name="fk_workspaces_tenant_id_tenants",
        ),
    )
    op.create_index("ix_workspaces_tenant_id", "workspaces", ["tenant_id"])

    # -----------------------------------------------------------------
    # 3. memberships — with PARTIAL UNIQUE INDEXES (§7.1)
    # -----------------------------------------------------------------
    # See the long comment in src/db/models.py::Membership. The two
    # partial unique indexes below are the schema-level enforcement of
    # plan v0.5.1 MF-1.
    # -----------------------------------------------------------------
    op.create_table(
        "memberships",
        sa.Column(
            "id",
            UUID(as_uuid=False),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("tenant_id", UUID(as_uuid=False), nullable=False),
        sa.Column("user_id", sa.String(255), nullable=False),
        sa.Column("workspace_id", UUID(as_uuid=False), nullable=True),
        sa.Column("role", sa.String(32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            ondelete="CASCADE",
            name="fk_memberships_tenant_id_tenants",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            ondelete="CASCADE",
            name="fk_memberships_workspace_id_workspaces",
        ),
        sa.CheckConstraint(
            "role IN ('owner','admin','member','viewer','service_account')",
            name="ck_memberships_role",
        ),
    )
    # §7.1 partial unique index: tenant-level rows
    op.create_index(
        "uq_memberships_tenant_level",
        "memberships",
        ["tenant_id", "user_id"],
        unique=True,
        postgresql_where=sa.text("workspace_id IS NULL"),
    )
    # §7.1 partial unique index: workspace-level rows
    op.create_index(
        "uq_memberships_workspace_level",
        "memberships",
        ["tenant_id", "user_id", "workspace_id"],
        unique=True,
        postgresql_where=sa.text("workspace_id IS NOT NULL"),
    )
    # Lookup indexes for authz queries
    op.create_index(
        "ix_memberships_lookup_workspace",
        "memberships",
        ["tenant_id", "user_id", "workspace_id"],
    )
    op.create_index(
        "ix_memberships_lookup_tenant",
        "memberships",
        ["tenant_id", "user_id"],
        postgresql_where=sa.text("workspace_id IS NULL"),
    )

    # Canonical §7.1 comment block on the table itself, so anyone
    # inspecting the schema via psql \d+ or a tool like DBeaver sees it.
    op.execute(
        """
        COMMENT ON TABLE memberships IS
        'Memberships authorization model. '
        'workspace_id IS NULL means tenant-level membership (org-wide actions). '
        'workspace_id IS NOT NULL means workspace-level membership. '
        'A user may have one tenant-level row AND N workspace-level rows. '
        'Enforced by two partial unique indexes (uq_memberships_tenant_level, '
        'uq_memberships_workspace_level) rather than a single full-tuple unique '
        'constraint because Postgres treats NULL as distinct in unique constraints, '
        'which would permit duplicate tenant-level rows and break authz. '
        'See plan v0.5.1 §7.1.'
        """
    )

    # -----------------------------------------------------------------
    # 4. service_accounts — reserved
    # -----------------------------------------------------------------
    op.create_table(
        "service_accounts",
        sa.Column(
            "id",
            UUID(as_uuid=False),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("tenant_id", UUID(as_uuid=False), nullable=False),
        sa.Column("workspace_id", UUID(as_uuid=False), nullable=True),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("public_id", sa.String(255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            ondelete="CASCADE",
            name="fk_service_accounts_tenant_id_tenants",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            ondelete="CASCADE",
            name="fk_service_accounts_workspace_id_workspaces",
        ),
        sa.UniqueConstraint("public_id", name="uq_service_accounts_public_id"),
    )
    op.create_index("ix_service_accounts_tenant_id", "service_accounts", ["tenant_id"])

    # -----------------------------------------------------------------
    # 5. api_keys — reserved
    # -----------------------------------------------------------------
    op.create_table(
        "api_keys",
        sa.Column(
            "id",
            UUID(as_uuid=False),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("tenant_id", UUID(as_uuid=False), nullable=False),
        sa.Column("workspace_id", UUID(as_uuid=False), nullable=True),
        sa.Column("service_account_id", UUID(as_uuid=False), nullable=True),
        sa.Column("key_hash", sa.String(128), nullable=False),
        sa.Column("prefix", sa.String(16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            ondelete="CASCADE",
            name="fk_api_keys_tenant_id_tenants",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            ondelete="CASCADE",
            name="fk_api_keys_workspace_id_workspaces",
        ),
        sa.ForeignKeyConstraint(
            ["service_account_id"],
            ["service_accounts.id"],
            ondelete="CASCADE",
            name="fk_api_keys_service_account_id_service_accounts",
        ),
        sa.UniqueConstraint("key_hash", name="uq_api_keys_key_hash"),
    )
    op.create_index("ix_api_keys_tenant_id", "api_keys", ["tenant_id"])

    # -----------------------------------------------------------------
    # 6. assets
    # -----------------------------------------------------------------
    op.create_table(
        "assets",
        sa.Column(
            "id",
            UUID(as_uuid=False),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("tenant_id", UUID(as_uuid=False), nullable=False),
        sa.Column("workspace_id", UUID(as_uuid=False), nullable=False),
        sa.Column("asset_type", sa.String(32), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("slug", sa.String(100), nullable=False),
        sa.Column(
            "description", sa.Text(), nullable=False, server_default=sa.text("''")
        ),
        sa.Column("version", sa.Integer(), nullable=False, server_default=sa.text("1")),
        sa.Column(
            "status",
            sa.String(16),
            nullable=False,
            server_default=sa.text("'draft'"),
        ),
        sa.Column("content_hash", sa.String(128), nullable=False),
        sa.Column(
            "storage_tier",
            sa.String(16),
            nullable=False,
            server_default=sa.text("'inline'"),
        ),
        sa.Column("inline_content", JSONB, nullable=True),
        sa.Column("payload_backend", sa.String(16), nullable=True),
        sa.Column("payload_bucket", sa.String(255), nullable=True),
        sa.Column("payload_key", sa.Text(), nullable=True),
        sa.Column("payload_size_bytes", sa.Integer(), nullable=True),
        # Governance actors (plan §2.6 — VARCHAR for Clerk sub / reserved IDs)
        sa.Column("created_by_actor_id", sa.String(255), nullable=False),
        sa.Column("created_by_actor_type", sa.String(20), nullable=False),
        sa.Column("created_by_display", sa.String(255), nullable=True),
        sa.Column("approved_by_actor_id", sa.String(255), nullable=True),
        sa.Column("approved_by_actor_type", sa.String(20), nullable=True),
        sa.Column("approved_by_display", sa.String(255), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "changelog", sa.Text(), nullable=False, server_default=sa.text("''")
        ),
        # Lineage
        sa.Column("cloned_from", UUID(as_uuid=False), nullable=True),
        sa.Column("parent_version", sa.Integer(), nullable=True),
        # Metadata
        sa.Column(
            "tags",
            JSONB,
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            ondelete="CASCADE",
            name="fk_assets_tenant_id_tenants",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            ondelete="CASCADE",
            name="fk_assets_workspace_id_workspaces",
        ),
        sa.CheckConstraint(
            "asset_type IN ("
            "'judge_pack','policy_pack','scenario_pack','workflow_pack',"
            "'dataset','bot_profile','scorecard'"
            ")",
            name="ck_assets_asset_type",
        ),
        sa.CheckConstraint(
            "status IN ('draft','approved','deprecated')",
            name="ck_assets_status",
        ),
        sa.CheckConstraint(
            "storage_tier IN ('inline','object')",
            name="ck_assets_storage_tier",
        ),
        sa.CheckConstraint(
            "created_by_actor_type IN ('human','service_account','system','support')",
            name="ck_assets_created_by_actor_type",
        ),
    )
    # Tenant-scoped uniqueness on (slug, asset_type, version) via a partial
    # unique index scoped to workspace. Distinct version ladders per asset
    # type so judge_pack:greeting@v1 and policy_pack:greeting@v1 can coexist.
    op.create_index(
        "uq_assets_tenant_slug_type_version",
        "assets",
        ["tenant_id", "workspace_id", "asset_type", "slug", "version"],
        unique=True,
    )
    op.create_index(
        "ix_assets_tenant_workspace", "assets", ["tenant_id", "workspace_id"]
    )
    op.create_index("ix_assets_tenant_type", "assets", ["tenant_id", "asset_type"])

    # -----------------------------------------------------------------
    # 7. runs — 11-state enum (plan §2.7)
    # -----------------------------------------------------------------
    op.create_table(
        "runs",
        sa.Column(
            "id",
            UUID(as_uuid=False),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("tenant_id", UUID(as_uuid=False), nullable=False),
        sa.Column("workspace_id", UUID(as_uuid=False), nullable=False),
        sa.Column("status", sa.String(32), nullable=False),
        sa.Column("initiated_by_actor_id", sa.String(255), nullable=False),
        sa.Column("engine_version", sa.String(64), nullable=False),
        sa.Column(
            "asset_versions",
            JSONB,
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "judge_scores",
            JSONB,
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "metadata",
            JSONB,
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            ondelete="CASCADE",
            name="fk_runs_tenant_id_tenants",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            ondelete="CASCADE",
            name="fk_runs_workspace_id_workspaces",
        ),
        sa.CheckConstraint(
            "status IN ("
            "'queued','provisioning','running','finalizing',"
            "'completed','failed','cancelled',"
            "'waiting_input','paused','expired','unknown'"
            ")",
            name="ck_runs_status",
        ),
    )
    op.create_index("ix_runs_tenant_workspace", "runs", ["tenant_id", "workspace_id"])
    op.create_index("ix_runs_tenant_status", "runs", ["tenant_id", "status"])
    op.create_index("ix_runs_created_at", "runs", ["created_at"])

    # -----------------------------------------------------------------
    # 8. conversation_summaries
    # -----------------------------------------------------------------
    op.create_table(
        "conversation_summaries",
        sa.Column(
            "id",
            UUID(as_uuid=False),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("tenant_id", UUID(as_uuid=False), nullable=False),
        sa.Column("workspace_id", UUID(as_uuid=False), nullable=False),
        sa.Column("run_id", UUID(as_uuid=False), nullable=False),
        # Persona / bot context
        sa.Column("persona_id", sa.String(255), nullable=False),
        sa.Column("persona_name", sa.String(255), nullable=False),
        sa.Column(
            "persona_type",
            sa.String(64),
            nullable=False,
            server_default=sa.text("'standard'"),
        ),
        # Verdict + scores
        sa.Column(
            "verdict",
            sa.String(16),
            nullable=False,
            server_default=sa.text("'pending'"),
        ),
        sa.Column(
            "pass_rate",
            sa.Float(),
            nullable=False,
            server_default=sa.text("0.0"),
        ),
        sa.Column(
            "turn_count", sa.Integer(), nullable=False, server_default=sa.text("0")
        ),
        # Service-generated aggregated judge scores (§2.8 — not user-writable)
        sa.Column(
            "judge_scores",
            JSONB,
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        # Failure metadata
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("failure_category", sa.String(128), nullable=True),
        # Full transcript in object storage (R2 or local)
        sa.Column("transcript_backend", sa.String(16), nullable=True),
        sa.Column("transcript_bucket", sa.String(255), nullable=True),
        sa.Column("transcript_key", sa.Text(), nullable=True),
        # User-writable metadata — Turn 2 wraps in SafeJSONB
        sa.Column(
            "tags",
            JSONB,
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            ondelete="CASCADE",
            name="fk_conversation_summaries_tenant_id_tenants",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            ondelete="CASCADE",
            name="fk_conversation_summaries_workspace_id_workspaces",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            ondelete="CASCADE",
            name="fk_conversation_summaries_run_id_runs",
        ),
        sa.CheckConstraint(
            "verdict IN ('pass','fail','error','pending')",
            name="ck_conversation_summaries_verdict",
        ),
        sa.CheckConstraint(
            "pass_rate >= 0.0 AND pass_rate <= 1.0",
            name="ck_conversation_summaries_pass_rate",
        ),
    )
    op.create_index(
        "ix_conv_sum_tenant_workspace",
        "conversation_summaries",
        ["tenant_id", "workspace_id"],
    )
    op.create_index("ix_conv_sum_run_id", "conversation_summaries", ["run_id"])

    # -----------------------------------------------------------------
    # 9. dashboard_artifacts
    # -----------------------------------------------------------------
    op.create_table(
        "dashboard_artifacts",
        sa.Column(
            "id",
            UUID(as_uuid=False),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("tenant_id", UUID(as_uuid=False), nullable=False),
        sa.Column("workspace_id", UUID(as_uuid=False), nullable=False),
        sa.Column("run_id", UUID(as_uuid=False), nullable=False),
        sa.Column("artifact_type", sa.String(64), nullable=False),
        sa.Column(
            "payload",
            JSONB,
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            ondelete="CASCADE",
            name="fk_dashboard_artifacts_tenant_id_tenants",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            ondelete="CASCADE",
            name="fk_dashboard_artifacts_workspace_id_workspaces",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            ondelete="CASCADE",
            name="fk_dashboard_artifacts_run_id_runs",
        ),
    )
    op.create_index(
        "ix_dashboard_artifacts_run_id", "dashboard_artifacts", ["run_id"]
    )
    op.create_index(
        "ix_dashboard_artifacts_tenant_workspace",
        "dashboard_artifacts",
        ["tenant_id", "workspace_id"],
    )

    # -----------------------------------------------------------------
    # 10. comparisons
    # -----------------------------------------------------------------
    op.create_table(
        "comparisons",
        sa.Column(
            "id",
            UUID(as_uuid=False),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("tenant_id", UUID(as_uuid=False), nullable=False),
        sa.Column("workspace_id", UUID(as_uuid=False), nullable=False),
        sa.Column("left_run_id", UUID(as_uuid=False), nullable=False),
        sa.Column("right_run_id", UUID(as_uuid=False), nullable=False),
        sa.Column(
            "status",
            sa.String(32),
            nullable=False,
            server_default=sa.text("'pending'"),
        ),
        sa.Column("initiated_by_actor_id", sa.String(255), nullable=False),
        sa.Column(
            "engine_version",
            sa.String(64),
            nullable=False,
            server_default=sa.text("'engine_v1'"),
        ),
        # User-writable config — Turn 2 wraps in SafeJSONB
        sa.Column(
            "config",
            JSONB,
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        # Service-generated — NOT user-writable (§2.8)
        sa.Column(
            "regression_signals",
            JSONB,
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
        sa.Column("left_provenance", JSONB, nullable=True),
        sa.Column("right_provenance", JSONB, nullable=True),
        sa.Column("metric_deltas", JSONB, nullable=True),
        # Reserved for heavy artifacts (plan §M2 — always None in 6a)
        sa.Column("result_bucket", sa.String(255), nullable=True),
        sa.Column("result_key", sa.Text(), nullable=True),
        # Verdict + comparison profile
        sa.Column("verdict", sa.String(16), nullable=True),
        sa.Column("evidence_count", sa.Integer(), nullable=True),
        sa.Column("comparison_profile", sa.String(64), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            ondelete="CASCADE",
            name="fk_comparisons_tenant_id_tenants",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            ondelete="CASCADE",
            name="fk_comparisons_workspace_id_workspaces",
        ),
        sa.ForeignKeyConstraint(
            ["left_run_id"],
            ["runs.id"],
            ondelete="CASCADE",
            name="fk_comparisons_left_run_id_runs",
        ),
        sa.ForeignKeyConstraint(
            ["right_run_id"],
            ["runs.id"],
            ondelete="CASCADE",
            name="fk_comparisons_right_run_id_runs",
        ),
        sa.CheckConstraint(
            "status IN ('pending','running','completed','failed')",
            name="ck_comparisons_status",
        ),
        sa.CheckConstraint(
            "verdict IS NULL OR verdict IN ('regression','improvement','neutral','inconclusive')",
            name="ck_comparisons_verdict",
        ),
    )
    op.create_index(
        "ix_comparisons_tenant_workspace",
        "comparisons",
        ["tenant_id", "workspace_id"],
    )
    op.create_index("ix_comparisons_left_run_id", "comparisons", ["left_run_id"])
    op.create_index("ix_comparisons_right_run_id", "comparisons", ["right_run_id"])

    # -----------------------------------------------------------------
    # 11. idempotency_keys
    # -----------------------------------------------------------------
    op.create_table(
        "idempotency_keys",
        sa.Column(
            "id",
            UUID(as_uuid=False),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("tenant_id", UUID(as_uuid=False), nullable=False),
        sa.Column("idempotency_key", sa.String(255), nullable=False),
        sa.Column("request_hash", sa.String(128), nullable=False),
        sa.Column(
            "response_payload",
            JSONB,
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            ondelete="CASCADE",
            name="fk_idempotency_keys_tenant_id_tenants",
        ),
    )
    op.create_index(
        "uq_idempotency_keys_tenant_key",
        "idempotency_keys",
        ["tenant_id", "idempotency_key"],
        unique=True,
    )

    # -----------------------------------------------------------------
    # 12. audit_events — PARTITIONED (monthly + DEFAULT) — §7.2
    # -----------------------------------------------------------------
    # Hand-written CREATE TABLE because the declarative layer doesn't
    # model PARTITION BY. All columns must also appear in the ORM model
    # (src/db/models.py::AuditEvent) for SQLAlchemy to read/write them.
    # -----------------------------------------------------------------
    op.execute(
        """
        CREATE TABLE audit_events (
            id              UUID NOT NULL DEFAULT gen_random_uuid(),
            tenant_id       UUID NOT NULL REFERENCES tenants(id),
            action          VARCHAR(100) NOT NULL,
            resource_type   VARCHAR(50),
            resource_id     VARCHAR(255),
            actor_id        VARCHAR(255) NOT NULL,
            actor_type      VARCHAR(20) NOT NULL,
            actor_display   VARCHAR(255),
            workspace_id    UUID REFERENCES workspaces(id),
            details         JSONB NOT NULL DEFAULT '{}'::jsonb,
            asset_versions  JSONB,
            ip_address      INET,
            user_agent      TEXT,
            correlation_id  VARCHAR(100),
            created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
            PRIMARY KEY (id, created_at),
            CONSTRAINT ck_audit_events_actor_type CHECK (
                actor_type IN ('human','service_account','system','support')
            )
        ) PARTITION BY RANGE (created_at)
        """
    )
    # Monthly partitions for the current two months
    op.execute(
        """
        CREATE TABLE audit_events_2026_04 PARTITION OF audit_events
            FOR VALUES FROM ('2026-04-01') TO ('2026-05-01')
        """
    )
    op.execute(
        """
        CREATE TABLE audit_events_2026_05 PARTITION OF audit_events
            FOR VALUES FROM ('2026-05-01') TO ('2026-06-01')
        """
    )
    # DEFAULT partition — the v0.4 MF-5 fix. Any row outside the monthly
    # ranges lands here instead of failing the write.
    op.execute(
        """
        CREATE TABLE audit_events_default PARTITION OF audit_events DEFAULT
        """
    )
    # Indexes on the parent partitioned table — automatically applied to
    # every partition created above and to any future partitions.
    op.execute(
        "CREATE INDEX ix_audit_events_tenant_time ON audit_events "
        "(tenant_id, created_at)"
    )
    op.execute(
        "CREATE INDEX ix_audit_events_action ON audit_events "
        "(action, created_at)"
    )
    op.execute(
        "CREATE INDEX ix_audit_events_correlation ON audit_events "
        "(correlation_id) WHERE correlation_id IS NOT NULL"
    )

    # -----------------------------------------------------------------
    # Application role + RLS policies (plan §5)
    # -----------------------------------------------------------------
    # Create the app_user role if it doesn't exist. This is the role the
    # application connects as — it is NOT a superuser, so RLS policies
    # apply to it. FORCE makes RLS also apply to the table owner.
    # -----------------------------------------------------------------
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_user') THEN
                CREATE ROLE app_user NOLOGIN;
            END IF;
        END
        $$
        """
    )
    op.execute("GRANT USAGE ON SCHEMA public TO app_user")
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app_user")
    op.execute("GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app_user")
    op.execute(
        "ALTER DEFAULT PRIVILEGES IN SCHEMA public "
        "GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_user"
    )

    # Enable + FORCE RLS on every tenant-scoped table, plus a tenant
    # isolation policy keyed off app.current_tenant_id.
    for table in RLS_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation_{table} ON {table}
                USING      (tenant_id = current_setting('app.current_tenant_id', true)::uuid)
                WITH CHECK (tenant_id = current_setting('app.current_tenant_id', true)::uuid)
            """
        )

    # audit_events is append-only at the policy layer as well: explicitly
    # forbid UPDATE and DELETE for any role subject to RLS. These MUST be
    # RESTRICTIVE policies — by default, multiple permissive policies on
    # the same command are OR'd together, which would mean the
    # tenant_isolation policy's USING clause would still allow rows
    # through. RESTRICTIVE policies are AND'd after the OR of permissive
    # policies, so `(tenant_matches OR ...) AND false = false` — UPDATE
    # and DELETE are unconditionally blocked on audit_events.
    op.execute(
        "CREATE POLICY audit_events_no_update ON audit_events "
        "AS RESTRICTIVE FOR UPDATE USING (false)"
    )
    op.execute(
        "CREATE POLICY audit_events_no_delete ON audit_events "
        "AS RESTRICTIVE FOR DELETE USING (false)"
    )


def downgrade() -> None:
    # Reverse order — drop everything including the role.
    # Policies are implicitly dropped when their tables are dropped.

    op.execute("DROP TABLE IF EXISTS audit_events_default CASCADE")
    op.execute("DROP TABLE IF EXISTS audit_events_2026_05 CASCADE")
    op.execute("DROP TABLE IF EXISTS audit_events_2026_04 CASCADE")
    op.execute("DROP TABLE IF EXISTS audit_events CASCADE")

    op.drop_table("idempotency_keys")
    op.drop_table("comparisons")
    op.drop_table("dashboard_artifacts")
    op.drop_table("conversation_summaries")
    op.drop_table("runs")
    op.drop_table("assets")
    op.drop_table("api_keys")
    op.drop_table("service_accounts")
    op.drop_table("memberships")
    op.drop_table("workspaces")
    op.drop_table("tenants")

    # Drop the role LAST — after every table has been dropped. We use
    # `DROP OWNED BY` to remove any lingering grants the role holds on
    # surviving objects (notably alembic_version, which is created by
    # alembic itself and survives the migration downgrade) and on
    # default privileges configured via ALTER DEFAULT PRIVILEGES. Without
    # DROP OWNED BY, DROP ROLE fails with DependentObjectsStillExistError
    # because the role still holds privileges on alembic_version.
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_user') THEN
                -- Revoke default-privilege grants we configured at upgrade
                ALTER DEFAULT PRIVILEGES IN SCHEMA public
                    REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM app_user;
                ALTER DEFAULT PRIVILEGES IN SCHEMA public
                    REVOKE USAGE, SELECT ON SEQUENCES FROM app_user;
                -- Drop any object-level grants this role still holds
                -- (notably on alembic_version, which survives downgrade)
                DROP OWNED BY app_user;
                DROP ROLE app_user;
            END IF;
        END
        $$
        """
    )
